// Generated by CoffeeScript 1.3.3
var hideAddressBar;

document.addEventListener('touchmove', function(e) {
  return e.preventDefault();
});

hideAddressBar = function() {
  var doit,
    _this = this;
  doit = function() {
    return window.scrollTo(0, 1);
  };
  setTimeout(doit, 500);
  return $(window).bind('resize', doit);
};

$(document.body).toggleClass((navigator.userAgent.match(/iP(od|ad|hone)/i) ? window.navigator.standalone ? 'IOSFullScreen' : (hideAddressBar(), 'IOS') : (hideAddressBar(), 'ANDROID')), true);

define(['__', 'cell-mobile/Nav', 'cell!./TitleBar', 'cell!./Content', 'cell!./TabBar', 'Preloads'], function(__, Nav, TitleBar, Content, TabBar) {
  return {
    render_el: function() {
      var _this = this;
      return [
        __(TitleBar), __(Content, {
          location_uid_loaded: function(location_uid) {
            return _this._done_loading_location_uid(location_uid);
          }
        }), __(TabBar)
      ];
    },
    after_render: function() {
      var _this = this;
      return Nav.start(function(_done_loading_location_uid) {
        _this._done_loading_location_uid = _done_loading_location_uid;
      });
    }
  };
});
