// Generated by CoffeeScript 1.3.3

define(function() {
  var PageViewModel, _registry;
  _registry = {};
  PageViewModel = function(_arg) {
    this.location = _arg.location;
    return this.title = 'Loading...';
  };
  PageViewModel.for_location = function(location) {
    var _name;
    if ((location != null ? location.uid : void 0) != null) {
      return _registry[_name = location.uid] || (_registry[_name] = new PageViewModel({
        location: location
      }));
    }
  };
  _.extend(PageViewModel.prototype, Backbone.Events, {
    set_title: function(new_title) {
      var old_title;
      if (this.title !== new_title) {
        old_title = this.title;
        this.title = new_title;
        return this.trigger('change:title', this.title, old_title);
      }
    }
  });
  return PageViewModel;
});
