// Generated by CoffeeScript 1.3.3

define(['__', 'cell-mobile/Nav', './PageViewModel'], function(__, Nav, PageViewModel) {
  return {
    render_el: function() {
      return [this.options.location.has_referrer ? __('.backbutton', 'Back', __('.actual', 'Back')) : void 0, this.$title = __.$('.title')];
    },
    after_render: function() {
      var _this = this;
      return PageViewModel.for_location(this.options.location).on('change:title', function(title) {
        return _this.$title.html(title);
      });
    },
    events: {
      'tap .backbutton': function() {
        return Nav.go_to_referrer(this.options.location.uid);
      }
    }
  };
});
