// Generated by CoffeeScript 1.3.3

define(['__', 'cell-mobile/Nav'], function(__, Nav) {
  var tabs;
  tabs = {
    recipes: 'Recipes',
    calendar: 'Calendar',
    pantry: 'Pantry',
    groceries: 'Groceries'
  };
  return {
    tagName: 'ul',
    render_el: function() {
      var label, tab, _results;
      _results = [];
      for (tab in tabs) {
        label = tabs[tab];
        _results.push(__('li.tab', {
          'data-tab': tab
        }, __('.tab-label', label)));
      }
      return _results;
    },
    after_render: function() {
      var _this = this;
      return Nav.on('change:location', function(location, prev_location, _arg) {
        var is_switch_tab;
        is_switch_tab = _arg.is_switch_tab;
        if (is_switch_tab) {
          _this.$('li.active').removeClass('active');
          return _this.$("li[data-tab=" + location.tab + "]").addClass('active');
        }
      });
    },
    events: {
      'tap li.tab': function(_arg) {
        var target;
        target = _arg.target;
        return Nav.switch_tab($(target).closest('li.tab').data('tab'));
      }
    }
  };
});
