// Generated by CoffeeScript 1.3.3

define(['__', 'cell-mobile/Nav', 'cell!./PageTitleBar'], function(__, Nav, PageTitleBar) {
  return {
    after_render: function() {
      var _this = this;
      return Nav.on('change:location', function(cur_location, prev_location, _arg) {
        var $prev_page_title_bar, is_back, is_switch_tab;
        is_back = _arg.is_back, is_switch_tab = _arg.is_switch_tab;
        if (is_switch_tab) {
          if (prev_location) {
            _this.$tab(prev_location.tab).removeClass('active');
          }
          _this.$tab(cur_location.tab).addClass('active');
          return _this.$page_title_bar(cur_location).addClass('active').removeClass('slide-out-fade slide-out-fade-reverse slide-in-fade slide-in-fade-reverse');
        } else {
          if (prev_location) {
            ($prev_page_title_bar = _this.$page_title_bar(prev_location)).removeClass('active slide-in-fade slide-in-fade-reverse').addClass("slide-out-fade" + (is_back && '-reverse' || ''));
          }
          return _this.$page_title_bar(cur_location).removeClass('slide-out-fade slide-out-fade-reverse').addClass("active slide-in-fade" + (is_back && '-reverse' || ''));
        }
      });
    },
    $page_title_bar: function(location) {
      var $page_title_bar;
      $page_title_bar = this.$el.children(".tab[data-tab='" + location.tab + "']").children(".PageTitleBar[data-location-uid='" + location.uid + "']");
      if ($page_title_bar[0]) {
        return $page_title_bar;
      } else {
        return __.$(PageTitleBar, {
          location: location
        }).attr('data-location-uid', location.uid).appendTo(this.$tab(location.tab));
      }
    },
    $tab: function(tab) {
      var $tab;
      if (($tab = this.$el.children(".tab[data-tab='" + tab + "']"))[0]) {
        return $tab;
      } else {
        return __.$('.tab', {
          'data-tab': tab
        }).appendTo(this.$el);
      }
    },
    events: {
      'webkitAnimationEnd .tab > .PageTitleBar.slide-out-fade,.PageTitleBar.slide-out-fade-reverse': function(_arg) {
        var target;
        target = _arg.target;
        return $(target).removeClass('slide-out-fade slide-out-fade-reverse');
      },
      'webkitAnimationEnd .tab > .PageTitleBar.slide-out-fade-reverse': function(_arg) {
        var target;
        target = _arg.target;
        return $(target).remove();
      }
    }
  };
});
