// Generated by CoffeeScript 1.3.3

define(['__', 'Nav'], function(__, Nav) {
  return {
    render_title_bar: function(_salt) {
      return __('.titlebar', {
        'data-_salt': _salt
      }, __(''));
    },
    render_el: function() {
      return [this.$cur = __.$('.current', this.$cur_backbutton = __.$('.backbutton', 'Back', __('.actual', 'Back')), this.$cur_title = __.$('.title')), this.$prev = __.$('.previous', this.$prev_backbutton = __.$('.backbutton', 'Back', __('.actual', 'Back')), this.$prev_title = __.$('.title'))];
    },
    after_render: function() {
      var animating, cur_salt,
        _this = this;
      animating = false;
      cur_salt = Nav.attributes._salt;
      this.$cur.on('webkitAnimationEnd', function() {
        animating = false;
        _this.$cur.toggleClass('slide-in-fade slide-in-fade-reverse', false);
        _this.$prev.toggleClass('slide-out-fade slide-out-fade-reverse', false);
        return false;
      });
      Nav.on('change:title', function() {
        if (cur_salt === Nav.attributes._salt) {
          return _this.$cur_title.html(Nav.attributes.title || 'Loading...');
        }
      });
      return Nav.on('change:_salt', function(model, _salt, _arg) {
        var changes, is_back, prev_backbutton_display, prev_title;
        changes = _arg.changes, is_back = _arg.is_back;
        cur_salt = _salt;
        prev_title = _this.$cur_title.html();
        prev_backbutton_display = _this.$cur_backbutton.css('display') === 'block';
        _this.$prev_backbutton.toggle(prev_backbutton_display);
        _this.$cur_backbutton.toggle(Nav.can_go_back());
        if (!animating && !(changes.tab != null)) {
          animating = true;
          _this.$cur.toggleClass("slide-in-fade" + (is_back && '-reverse' || ''), true);
          if (prev_title) {
            _this.$prev.toggleClass("slide-out-fade" + (is_back && '-reverse' || ''), true);
            _this.$prev_title.html(prev_title);
          }
        }
        return _this.$cur_title.html(Nav.attributes.title || 'Loading...');
      });
    },
    events: {
      'click .backbutton': function() {
        return Nav.go_back();
      }
    }
  };
});
