// Generated by CoffeeScript 1.3.3

define(['__', 'cell-mobile/Nav'], function(__, Nav) {
  return {
    initialize: function() {
      return this.model.set_title('Calendar');
    },
    render_el: function() {
      return "Calendar Page";
    }
  };
});
