// Generated by CoffeeScript 1.3.3

define(['__', 'cell-mobile/Nav'], function(__, Nav) {
  return {
    initialize: function() {
      return this.model.set_title("Recipe " + this.model.location.data.id);
    },
    render_el: function() {
      return 'Recipe Page';
    }
  };
});
