// Generated by CoffeeScript 1.3.3

define(['__', 'cell-mobile/Nav'], function(__, Nav) {
  return {
    initialize: function() {
      return this.model.set_title('Recipes');
    },
    render_el: function() {
      var i, _i, _results;
      _results = [];
      for (i = _i = 0; _i <= 100; i = ++_i) {
        _results.push(__('a.recipe', {
          'data-recipeid': i
        }, "Recipe #" + i));
      }
      return _results;
    },
    events: {
      'tap a.recipe': function(_arg) {
        var id, target;
        target = _arg.target;
        if ((id = $(target).closest('a.recipe').data('recipeid')) != null) {
          return Nav.go_to({
            page: "RecipePage",
            data: {
              id: id
            }
          });
        }
      }
    }
  };
});
