// Generated by CoffeeScript 1.3.3

define(function() {
  var _uid;
  _uid = Math.random() * 10000 >> 0;
  return {
    mock_location: function(_arg) {
      var data, has_referrer, page, tab, uid, _ref;
      _ref = _arg != null ? _arg : {}, uid = _ref.uid, tab = _ref.tab, page = _ref.page, data = _ref.data, has_referrer = _ref.has_referrer;
      return {
        uid: (uid != null) || _uid++,
        tab: (tab != null) || "MockTab",
        page: (page != null) || "MockTab_Page",
        data: (data != null) || {},
        has_referrer: (has_referrer != null) || false
      };
    }
  };
});
