// Generated by CoffeeScript 1.3.3

define(['__', 'Nav', 'cell!views/TitleBar', 'cell!views/Content', 'cell!views/TabBar'], function(__, Nav, TitleBar, Content, TabBar) {
  return {
    render_el: function() {
      return [__(TitleBar), __(Content), __(TabBar)];
    },
    after_render: function() {
      return Nav.start();
    }
  };
});
