// Generated by CoffeeScript 1.3.3

define(['require', '__', 'Nav'], function(require, __, Nav) {
  var PageModel;
  PageModel = Backbone.Model.extend();
  return {
    render_el: function() {
      return this.$container = __.$('.container');
    },
    after_render: function() {
      var prev_container_height, prev_height, scroller,
        _this = this;
      scroller = new iScroll(this.el);
      prev_height = prev_container_height = -1;
      setInterval((function() {
        var container_height, height;
        container_height = _this.$container.height();
        height = _this.$el.height();
        if (container_height !== prev_container_height || height !== prev_height) {
          prev_container_height = container_height;
          prev_height = height;
          return scroller.refresh();
        }
      }), 500);
      return Nav.on('change:page', function(model, page, opts) {
        return require(["cell!views/pages/" + (page[0].toUpperCase() + page.slice(1))], function(PageCell) {
          (model = new PageModel).on('change:title', function(model, title) {
            if (page === Nav.get('page')) {
              return Nav.set('title', title);
            }
          });
          return _this.$container.empty().append(__(PageCell, {
            model: model
          }));
        });
      });
    }
  };
});
