// Generated by CoffeeScript 1.3.3

define(['__', 'Nav'], function(__, Nav) {
  var tabs;
  tabs = {
    recipes: 'Recipes',
    calendar: 'Calendar',
    pantry: 'Pantry',
    groceries: 'Groceries'
  };
  return {
    tagName: 'ul',
    render_el: function() {
      var label, tab, _results;
      _results = [];
      for (tab in tabs) {
        label = tabs[tab];
        _results.push(__('li.tab', {
          'data-tab': tab
        }, __('div', label)));
      }
      return _results;
    },
    after_render: function() {
      var _this = this;
      return Nav.on('change:tab', function(model, newTab) {
        _this.$('li.active').removeClass('active');
        return _this.$("li[data-tab=" + newTab + "]").addClass('active');
      });
    },
    events: {
      'click li.tab': function(_arg) {
        var target;
        target = _arg.target;
        return Nav.go({
          tab: $(target).closest('.tab').data('tab')
        });
      }
    }
  };
});
