// Generated by CoffeeScript 1.3.3

define(['__', 'Nav'], function(__, Nav) {
  return {
    render_el: function() {
      return [this.$backbutton = __.$('#backbutton', __.$('span', 'Back')), __('#titles', this.$title = __.$('#title'), this.$prevTitle = __.$('#prevtitle')), __('#gobutton', __('span', 'Do It'))];
    },
    after_render: function() {
      var animating,
        _this = this;
      animating = false;
      this.$title.bind('webkitAnimationEnd', function() {
        this.$title.attr('class', '');
        this.$prevTitle.attr('class', '');
        return animating = false;
      });
      Nav.on('change:title', function(model, title, opts) {
        return _this.$title.html(title);
      });
      return Nav.on('change', function(model, opts) {
        var isBack, prevTitle, rev;
        isBack = opts.isBack;
        prevTitle = model.previous('title');
        _this.$title.html(model.attributes.title || 'Loading...');
        if (!animating) {
          _this.$backbutton.css('visibility', Nav.can_go_back() && 'visible' || 'hidden');
          rev = isBack && '-reverse' || '';
          if (prevTitle) {
            _this.$prevTitle.html(prevTitle).attr('class', "animate headingOut" + rev);
          }
          _this.$title.attr('class', "animate headingIn" + rev);
          return animating = true;
        }
      });
    },
    events: {
      'click #backbutton': function() {
        return Nav.go_back();
      }
    }
  };
});
