// Generated by CoffeeScript 1.3.3

define(function() {
  var Movie;
  Movie = Backbone.Model.extend({
    initialize: function() {
      return this.url = "/movies/" + this.id;
    }
  });
  return Backbone.Collection.extend({
    model: Movie,
    url: "/movies"
  });
});
