/*
 RequireJS 2.0.4 Copyright (c) 2010-2012, The Dojo Foundation All Rights Reserved.
 Available via the MIT or new BSD license.
 see: http://github.com/jrburke/requirejs for details
*/
(function(i){String.prototype.trim===i&&(String.prototype.trim=function(){return this.replace(/^\s+/,"").replace(/\s+$/,"")});Array.prototype.reduce===i&&(Array.prototype.reduce=function(o){if(this===void 0||this===null)throw new TypeError;var n=Object(this),c=n.length>>>0,g=0,b;if(typeof o!="function")throw new TypeError;if(c==0&&arguments.length==1)throw new TypeError;if(arguments.length>=2)b=arguments[1];else{do{if(g in n){b=n[g++];break}if(++g>=c)throw new TypeError;}while(1)}for(;g<c;){g in n&&
(b=o.call(i,b,n[g],g,n));g++}return b})})();
var Zepto=function(){function i(e){return"[object Function]"==I.call(e)}function o(e){return e instanceof Object}function n(e){return o(e)&&e.__proto__==Object.prototype}function c(e){return e instanceof Array}function g(e){return"number"==typeof e.length}function b(e){return e.replace(/::/g,"/").replace(/([A-Z]+)([A-Z][a-z])/g,"$1_$2").replace(/([a-z\d])([A-Z])/g,"$1_$2").replace(/_/g,"-").toLowerCase()}function f(e){return e in s?s[e]:s[e]=RegExp("(^|\\s)"+e+"(\\s|$)")}function j(e,h){return h===
q?k(e):k(e).filter(h)}function l(e,h,a,d){return i(h)?h.call(e,a,d):h}function C(e,h){h(e);for(var a in e.childNodes)C(e.childNodes[a],h)}var q,p,k,t,v=[],x=v.slice,w=window.document,E={},s={},G=w.defaultView.getComputedStyle,K={"column-count":1,columns:1,"font-weight":1,"line-height":1,opacity:1,"z-index":1,zoom:1},d=/^\s*<(\w+|!)[^>]*>/,B=/<(?!area|br|col|embed|hr|img|input|link|meta|param)(([\w:]+)[^>]*)\/>/ig,L=[1,3,8,9,11],H=w.createElement("table"),a=w.createElement("tr"),m={tr:w.createElement("tbody"),
tbody:H,thead:H,tfoot:H,td:a,th:a,"*":w.createElement("div")},y=/complete|loaded|interactive/,M=/^\.([\w-]+)$/,O=/^#([\w-]+)$/,z=/^[\w-]+$/,I={}.toString,r={},F,h,N=w.createElement("div");r.matches=function(e,h){if(!e||1!==e.nodeType)return!1;var a=e.webkitMatchesSelector||e.mozMatchesSelector||e.oMatchesSelector||e.matchesSelector;if(a)return a.call(e,h);var d;d=e.parentNode;(a=!d)&&(d=N).appendChild(e);d=~r.qsa(d,h).indexOf(e);a&&N.removeChild(e);return d};F=function(e){return e.replace(/-+(.)?/g,
function(e,h){return h?h.toUpperCase():""})};h=function(e){return e.filter(function(h,a){return e.indexOf(h)==a})};r.fragment=function(e,h){e.replace&&(e=e.replace(B,"<$1></$2>"));h===q&&(h=d.test(e)&&RegExp.$1);h in m||(h="*");var a=m[h];a.innerHTML=""+e;return k.each(x.call(a.childNodes),function(){a.removeChild(this)})};r.Z=function(e,h){e=e||[];e.__proto__=arguments.callee.prototype;e.selector=h||"";return e};r.isZ=function(e){return e instanceof r.Z};r.init=function(e,h){if(e){if(i(e))return k(w).ready(e);
if(r.isZ(e))return e;var a;if(c(e))a=e.filter(function(e){return e!==q&&null!==e});else if(n(e))a=[k.extend({},e)],e=null;else if(0<=L.indexOf(e.nodeType)||e===window)a=[e],e=null;else if(d.test(e))a=r.fragment(e.trim(),RegExp.$1),e=null;else{if(h!==q)return k(h).find(e);a=r.qsa(w,e)}return r.Z(a,e)}return r.Z()};k=function(e,h){return r.init(e,h)};k.extend=function(e){x.call(arguments,1).forEach(function(h){for(p in h)h[p]!==q&&(e[p]=h[p])});return e};r.qsa=function(e,h){var a;return e===w&&O.test(h)?
(a=e.getElementById(RegExp.$1))?[a]:v:1!==e.nodeType&&9!==e.nodeType?v:x.call(M.test(h)?e.getElementsByClassName(RegExp.$1):z.test(h)?e.getElementsByTagName(h):e.querySelectorAll(h))};k.isFunction=i;k.isObject=o;k.isArray=c;k.isPlainObject=n;k.inArray=function(e,h,a){return v.indexOf.call(h,e,a)};k.trim=function(e){return e.trim()};k.uuid=0;k.map=function(e,h){var a,d=[],m;if(g(e))for(m=0;m<e.length;m++)a=h(e[m],m),null!=a&&d.push(a);else for(m in e)a=h(e[m],m),null!=a&&d.push(a);return 0<d.length?
k.fn.concat.apply([],d):d};k.each=function(e,h){var a;if(g(e))for(a=0;a<e.length&&!1!==h.call(e[a],a,e[a]);a++);else for(a in e)if(!1===h.call(e[a],a,e[a]))break;return e};window.JSON&&(k.parseJSON=JSON.parse);k.fn={forEach:v.forEach,reduce:v.reduce,push:v.push,indexOf:v.indexOf,concat:v.concat,map:function(e){return k.map(this,function(h,a){return e.call(h,a,h)})},slice:function(){return k(x.apply(this,arguments))},ready:function(e){y.test(w.readyState)?e(k):w.addEventListener("DOMContentLoaded",
function(){e(k)},false);return this},get:function(e){return e===q?x.call(this):this[e]},toArray:function(){return this.get()},size:function(){return this.length},remove:function(){return this.each(function(){this.parentNode!=null&&this.parentNode.removeChild(this)})},each:function(e){this.forEach(function(h,a){e.call(h,a,h)});return this},filter:function(e){return i(e)?this.not(this.not(e)):k([].filter.call(this,function(h){return r.matches(h,e)}))},add:function(e,a){return k(h(this.concat(k(e,a))))},
is:function(e){return this.length>0&&r.matches(this[0],e)},not:function(e){var h=[];if(i(e)&&e.call!==q)this.each(function(a){e.call(this,a)||h.push(this)});else{var a=typeof e=="string"?this.filter(e):g(e)&&i(e.item)?x.call(e):k(e);this.forEach(function(e){a.indexOf(e)<0&&h.push(e)})}return k(h)},eq:function(e){return e===-1?this.slice(e):this.slice(e,+e+1)},first:function(){var e=this[0];return e&&!o(e)?e:k(e)},last:function(){var e=this[this.length-1];return e&&!o(e)?e:k(e)},find:function(e){var h;
h=this.length==1?r.qsa(this[0],e):this.map(function(){return r.qsa(this,e)});return k(h)},closest:function(e,h){for(var a=this[0];a&&!r.matches(a,e);)a=a!==h&&a!==w&&a.parentNode;return k(a)},parents:function(e){for(var h=[],a=this;a.length>0;)a=k.map(a,function(e){if((e=e.parentNode)&&e!==w&&h.indexOf(e)<0){h.push(e);return e}});return j(h,e)},parent:function(e){return j(h(this.pluck("parentNode")),e)},children:function(e){return j(this.map(function(){return x.call(this.children)}),e)},contents:function(){return k(this.map(function(){return x.call(this.childNodes)}))},
siblings:function(e){return j(this.map(function(e,h){return x.call(h.parentNode.children).filter(function(e){return e!==h})}),e)},empty:function(){return this.each(function(){this.innerHTML=""})},pluck:function(e){return this.map(function(){return this[e]})},show:function(){return this.each(function(){this.style.display=="none"&&(this.style.display=null);if(G(this,"").getPropertyValue("display")=="none"){var e=this.style,h=this.nodeName,a,d;if(!E[h]){a=w.createElement(h);w.body.appendChild(a);d=G(a,
"").getPropertyValue("display");a.parentNode.removeChild(a);d=="none"&&(d="block");E[h]=d}e.display=E[h]}})},replaceWith:function(e){return this.before(e).remove()},wrap:function(e){return this.each(function(){k(this).wrapAll(k(e)[0].cloneNode(false))})},wrapAll:function(e){if(this[0]){k(this[0]).before(e=k(e));e.append(this)}return this},wrapInner:function(e){return this.each(function(){var h=k(this),a=h.contents();a.length?a.wrapAll(e):h.append(e)})},unwrap:function(){this.parent().each(function(){k(this).replaceWith(k(this).children())});
return this},clone:function(){return k(this.map(function(){return this.cloneNode(true)}))},hide:function(){return this.css("display","none")},toggle:function(e){return(e===q?this.css("display")=="none":e)?this.show():this.hide()},prev:function(e){return k(this.pluck("previousElementSibling")).filter(e||"*")},next:function(e){return k(this.pluck("nextElementSibling")).filter(e||"*")},html:function(e){return e===q?this.length>0?this[0].innerHTML:null:this.each(function(h){var a=this.innerHTML;k(this).empty().append(l(this,
e,h,a))})},text:function(e){return e===q?this.length>0?this[0].textContent:null:this.each(function(){this.textContent=e})},attr:function(e,h){var a;return typeof e=="string"&&h===q?this.length==0||this[0].nodeType!==1?q:e=="value"&&this[0].nodeName=="INPUT"?this.val():!(a=this[0].getAttribute(e))&&e in this[0]?this[0][e]:a:this.each(function(a){if(this.nodeType===1)if(o(e))for(p in e)this.setAttribute(p,e[p]);else this.setAttribute(e,l(this,h,a,this.getAttribute(e)))})},removeAttr:function(e){return this.each(function(){this.nodeType===
1&&this.removeAttribute(e)})},prop:function(e,h){return h===q?this[0]?this[0][e]:q:this.each(function(a){this[e]=l(this,h,a,this[e])})},data:function(e,h){var a=this.attr("data-"+b(e),h);return a!==null?a:q},val:function(e){return e===q?this.length>0?this[0].multiple?k(this[0]).find("option").filter(function(){return this.selected}).pluck("value"):this[0].value:q:this.each(function(h){this.value=l(this,e,h,this.value)})},offset:function(){if(this.length==0)return null;var e=this[0].getBoundingClientRect();
return{left:e.left+window.pageXOffset,top:e.top+window.pageYOffset,width:e.width,height:e.height}},css:function(e,h){if(h===q&&typeof e=="string")return this.length==0?q:this[0].style[F(e)]||G(this[0],"").getPropertyValue(e);var a="";for(p in e)typeof e[p]=="string"&&e[p]==""?this.each(function(){this.style.removeProperty(b(p))}):a=a+(b(p)+":"+(typeof e[p]=="number"&&!K[b(p)]?e[p]+"px":e[p])+";");typeof e=="string"&&(h==""?this.each(function(){this.style.removeProperty(b(e))}):a=b(e)+":"+(typeof h==
"number"&&!K[b(e)]?h+"px":h));return this.each(function(){this.style.cssText=this.style.cssText+(";"+a)})},index:function(h){return h?this.indexOf(k(h)[0]):this.parent().children().indexOf(this[0])},hasClass:function(h){return this.length<1?false:f(h).test(this[0].className)},addClass:function(h){return this.each(function(a){t=[];var d=this.className;l(this,h,a,d).split(/\s+/g).forEach(function(h){k(this).hasClass(h)||t.push(h)},this);t.length&&(this.className=this.className+((d?" ":"")+t.join(" ")))})},
removeClass:function(h){return this.each(function(a){if(h===q)return this.className="";t=this.className;l(this,h,a,t).split(/\s+/g).forEach(function(h){t=t.replace(f(h)," ")});this.className=t.trim()})},toggleClass:function(h,a){return this.each(function(d){d=l(this,h,d,this.className);(a===q?!k(this).hasClass(d):a)?k(this).addClass(d):k(this).removeClass(d)})}};["width","height"].forEach(function(h){k.fn[h]=function(a){var d,m=h.replace(/./,function(h){return h[0].toUpperCase()});return a===q?this[0]==
window?window["inner"+m]:this[0]==w?w.documentElement["offset"+m]:(d=this.offset())&&d[h]:this.each(function(d){var m=k(this);m.css(h,l(this,a,d,m[h]()))})}});["after","prepend","before","append"].forEach(function(h,a){k.fn[h]=function(){var h=k.map(arguments,function(h){return o(h)?h:r.fragment(h)});if(h.length<1)return this;var e=this.length,d=e>1,m=a<2;return this.each(function(N,y){for(var b=0;b<h.length;b++){var s=h[m?h.length-b-1:b];C(s,function(h){h.nodeName!=null&&(h.nodeName.toUpperCase()===
"SCRIPT"&&(!h.type||h.type==="text/javascript"))&&window.eval.call(window,h.innerHTML)});d&&N<e-1&&(s=s.cloneNode(true));var c=a%2?y:y.parentNode;c?c.insertBefore(s,!a?y.nextSibling:a==1?c.firstChild:a==2?y:null):k(s).remove()}})};k.fn[a%2?h+"To":"insert"+(a?"Before":"After")]=function(a){k(a)[h](this);return this}});r.Z.prototype=k.fn;r.camelize=F;r.uniq=h;k.zepto=r;return k}();window.Zepto=Zepto;"$"in window||(window.$=Zepto);
(function(i){function o(b){return b._zid||(b._zid=C++)}function n(b,f,g,j){f=c(f);if(f.ns)var s=RegExp("(?:^| )"+f.ns.replace(" "," .* ?")+"(?: |$)");return(l[o(b)]||[]).filter(function(b){return b&&(!f.e||b.e==f.e)&&(!f.ns||s.test(b.ns))&&(!g||o(b.fn)===o(g))&&(!j||b.sel==j)})}function c(b){b=(""+b).split(".");return{e:b[0],ns:b.slice(1).sort().join(" ")}}function g(b,c,f){i.isObject(b)?i.each(b,f):b.split(/\s/).forEach(function(b){f(b,c)})}function b(b,f,j,k,s,G){var G=!!G,K=o(b),d=l[K]||(l[K]=
[]);g(f,j,function(f,g){var j=s&&s(g,f),a=j||g,m=function(d){var m=a.apply(b,[d].concat(d.data));!1===m&&d.preventDefault();return m},j=i.extend(c(f),{fn:g,proxy:m,sel:k,del:j,i:d.length});d.push(j);b.addEventListener(j.e,m,G)})}function f(b,f,c,j){var s=o(b);g(f||"",c,function(f,c){n(b,f,c,j).forEach(function(d){delete l[s][d.i];b.removeEventListener(d.e,d.proxy,!1)})})}function j(b){var f=i.extend({originalEvent:b},b);i.each(t,function(c,g){f[c]=function(){this[g]=p;return b[c].apply(b,arguments)};
f[g]=k});return f}var l={},C=1,q={};q.click=q.mousedown=q.mouseup=q.mousemove="MouseEvents";i.event={add:b,remove:f};i.proxy=function(b,f){if(i.isFunction(b)){var c=function(){return b.apply(f,arguments)};c._zid=o(b);return c}if("string"==typeof f)return i.proxy(b[f],b);throw new TypeError("expected function");};i.fn.bind=function(f,c){return this.each(function(){b(this,f,c)})};i.fn.unbind=function(b,c){return this.each(function(){f(this,b,c)})};i.fn.one=function(c,g){return this.each(function(j,
i){b(this,c,g,null,function(b,c){return function(){var g=b.apply(i,arguments);f(i,c,b);return g}})})};var p=function(){return!0},k=function(){return!1},t={preventDefault:"isDefaultPrevented",stopImmediatePropagation:"isImmediatePropagationStopped",stopPropagation:"isPropagationStopped"};i.fn.delegate=function(c,f,g){var l=!1;if("blur"==f||"focus"==f)i.iswebkit?f="blur"==f?"focusout":"focus"==f?"focusin":f:l=!0;return this.each(function(s,k){b(k,f,g,c,function(b){return function(d){var f,s=i(d.target).closest(c,
k).get(0);if(s)return f=i.extend(j(d),{currentTarget:s,liveFired:k}),b.apply(s,[f].concat([].slice.call(arguments,1)))}},l)})};i.fn.undelegate=function(b,c,g){return this.each(function(){f(this,c,g,b)})};i.fn.live=function(b,f){i(document.body).delegate(this.selector,b,f);return this};i.fn.die=function(b,f){i(document.body).undelegate(this.selector,b,f);return this};i.fn.on=function(b,f,c){return void 0==f||i.isFunction(f)?this.bind(b,f||c):this.delegate(f,b,c)};i.fn.off=function(b,f,c){return void 0==
f||i.isFunction(f)?this.unbind(b,f||c):this.undelegate(f,b,c)};i.fn.trigger=function(b,f){"string"==typeof b&&(b=i.Event(b));var c=b;if(!("defaultPrevented"in c)){c.defaultPrevented=!1;var g=c.preventDefault;c.preventDefault=function(){this.defaultPrevented=!0;g.call(this)}}b.data=f;return this.each(function(){"dispatchEvent"in this&&this.dispatchEvent(b)})};i.fn.triggerHandler=function(b,f){var c,g;this.each(function(s,l){c=j("string"==typeof b?i.Event(b):b);c.data=f;c.target=l;i.each(n(l,b.type||
b),function(b,d){g=d.proxy(c);if(c.isImmediatePropagationStopped())return!1})});return g};"focusin focusout load resize scroll unload click dblclick mousedown mouseup mousemove mouseover mouseout change select keydown keypress keyup error".split(" ").forEach(function(b){i.fn[b]=function(f){return this.bind(b,f)}});["focus","blur"].forEach(function(b){i.fn[b]=function(f){if(f)this.bind(b,f);else if(this.length)try{this.get(0)[b]()}catch(c){}return this}});i.Event=function(b,f){var c=document.createEvent(q[b]||
"Events"),g=!0;if(f)for(var s in f)"bubbles"==s?g=!!f[s]:c[s]=f[s];c.initEvent(b,g,!0,null,null,null,null,null,null,null,null,null,null,null,null);return c}})(Zepto);
(function(i){function o(b,c,g,i){var n=Math.abs(b-c),o=Math.abs(g-i);return n>=o?0<b-c?"Left":"Right":0<g-i?"Up":"Down"}function n(){b=null;c.last&&(c.el.trigger("longTap"),c={})}var c={},g,b;i(document).ready(function(){var f,j;i(document.body).bind("touchstart",function(l){f=Date.now();j=f-(c.last||f);c.el=i("tagName"in l.touches[0].target?l.touches[0].target:l.touches[0].target.parentNode);g&&clearTimeout(g);c.x1=l.touches[0].pageX;c.y1=l.touches[0].pageY;0<j&&250>=j&&(c.isDoubleTap=!0);c.last=
f;b=setTimeout(n,750)}).bind("touchmove",function(f){b&&clearTimeout(b);b=null;c.x2=f.touches[0].pageX;c.y2=f.touches[0].pageY}).bind("touchend",function(){b&&clearTimeout(b);b=null;c.isDoubleTap?(c.el.trigger("doubleTap"),c={}):c.x2&&30<Math.abs(c.x1-c.x2)||c.y2&&30<Math.abs(c.y1-c.y2)?(c.el.trigger("swipe")&&c.el.trigger("swipe"+o(c.x1,c.x2,c.y1,c.y2)),c={}):"last"in c&&(c.el.trigger("tap"),g=setTimeout(function(){g=null;c.el.trigger("singleTap");c={}},250))}).bind("touchcancel",function(){g&&clearTimeout(g);
b&&clearTimeout(b);b=g=null;c={}})});"swipe swipeLeft swipeRight swipeUp swipeDown doubleTap tap singleTap longTap".split(" ").forEach(function(b){i.fn[b]=function(c){return this.bind(b,c)}})})(Zepto);
(function(){var i=Math,o=/webkit/i.test(navigator.appVersion)?"webkit":/firefox/i.test(navigator.userAgent)?"Moz":"opera"in window?"O":"";/android/gi.test(navigator.appVersion);var n=/iphone|ipad/gi.test(navigator.appVersion),c=/playbook/gi.test(navigator.appVersion),g=/hp-tablet/gi.test(navigator.appVersion),b="WebKitCSSMatrix"in window&&"m11"in new WebKitCSSMatrix,f="ontouchstart"in window&&!g,j=o+"Transform"in document.documentElement.style,l=n||c,C=window.requestAnimationFrame||window.webkitRequestAnimationFrame||
window.mozRequestAnimationFrame||window.oRequestAnimationFrame||window.msRequestAnimationFrame||function(b){return setTimeout(b,17)},q=window.cancelRequestAnimationFrame||window.webkitCancelAnimationFrame||window.webkitCancelRequestAnimationFrame||window.mozCancelRequestAnimationFrame||window.oCancelRequestAnimationFrame||window.msCancelRequestAnimationFrame||clearTimeout,p="onorientationchange"in window?"orientationchange":"resize",k=f?"touchstart":"mousedown",t=f?"touchmove":"mousemove",v=f?"touchend":
"mouseup",x=f?"touchcancel":"mouseup",w="translate"+(b?"3d(":"("),E=b?",0)":")",n=function(b,c){var g=document,d;this.wrapper="object"==typeof b?b:g.getElementById(b);this.wrapper.style.overflow="hidden";this.scroller=this.wrapper.children[0];this.options={hScroll:!0,vScroll:!0,x:0,y:0,bounce:!0,bounceLock:!1,momentum:!0,lockDirection:!0,useTransform:!0,useTransition:!1,onRefresh:null,onBeforeScrollStart:function(d){d.preventDefault()},onScrollStart:null,onBeforeScrollMove:null,onScrollMove:null,
onBeforeScrollEnd:null,onScrollEnd:null,onTouchEnd:null,onDestroy:null};for(d in c)this.options[d]=c[d];this.x=this.options.x;this.y=this.options.y;this.options.useTransform=j?this.options.useTransform:!1;this.options.hScrollbar=this.options.hScroll&&this.options.hScrollbar;this.options.vScrollbar=this.options.vScroll&&this.options.vScrollbar;this.options.useTransition=l&&this.options.useTransition;this.scroller.style[o+"TransitionProperty"]=this.options.useTransform?"-"+o.toLowerCase()+"-transform":
"top left";this.scroller.style[o+"TransitionDuration"]="0";this.scroller.style[o+"TransformOrigin"]="0 0";this.options.useTransition&&(this.scroller.style[o+"TransitionTimingFunction"]="cubic-bezier(0.33,0.66,0.66,1)");this.options.useTransform?this.scroller.style[o+"Transform"]=w+this.x+"px,"+this.y+"px"+E:this.scroller.style.cssText+=";position:absolute;top:"+this.y+"px;left:"+this.x+"px";this.refresh();this._bind(p,window);this._bind(k);f||this._bind("mouseout",this.wrapper)};n.prototype={enabled:!0,
x:0,y:0,steps:[],scale:1,handleEvent:function(b){switch(b.type){case k:if(!f&&0!==b.button)break;this._start(b);break;case t:this._move(b);break;case v:case x:this._end(b);break;case p:this._resize();break;case "mouseout":this._mouseout(b);break;case "webkitTransitionEnd":this._transitionEnd(b)}},_resize:function(){this.refresh()},_pos:function(b,c){b=this.hScroll?b:0;c=this.vScroll?c:0;this.options.useTransform?this.scroller.style[o+"Transform"]=w+b+"px,"+c+"px"+E+" scale("+this.scale+")":(b>>=0,
c>>=0,this.scroller.style.left=b+"px",this.scroller.style.top=c+"px");this.x=b;this.y=c},_start:function(b){var c=f?b.touches[0]:b,g,d;if(this.enabled){this.options.onBeforeScrollStart&&this.options.onBeforeScrollStart.call(this,b);this.options.useTransition&&this._transitionTime(0);this.zoomed=this.animating=this.moved=!1;this.dirY=this.dirX=this.absDistY=this.absDistX=this.distY=this.distX=0;if(this.options.momentum&&(this.options.useTransform?(g=getComputedStyle(this.scroller,null)[o+"Transform"].replace(/[^0-9-.,]/g,
"").split(","),d=1*g[4],g=1*g[5]):(d=1*getComputedStyle(this.scroller,null).left.replace(/[^0-9-]/g,""),g=1*getComputedStyle(this.scroller,null).top.replace(/[^0-9-]/g,"")),d!=this.x||g!=this.y))this.options.useTransition?this._unbind("webkitTransitionEnd"):q(this.aniTime),this.steps=[],this._pos(d,g);this.startX=this.x;this.startY=this.y;this.pointX=c.pageX;this.pointY=c.pageY;this.startTime=b.timeStamp||Date.now();this.options.onScrollStart&&this.options.onScrollStart.call(this,b);this._bind(t);
this._bind(v);this._bind(x)}},_move:function(b){var c=f?b.touches[0]:b,g=c.pageX-this.pointX,d=c.pageY-this.pointY,j=this.x+g,l=this.y+d,k=b.timeStamp||Date.now();this.options.onBeforeScrollMove&&this.options.onBeforeScrollMove.call(this,b);this.pointX=c.pageX;this.pointY=c.pageY;if(0<j||j<this.maxScrollX)j=this.options.bounce?this.x+g/2:0<=j||0<=this.maxScrollX?0:this.maxScrollX;if(0<l||l<this.maxScrollY)l=this.options.bounce?this.y+d/2:0<=l||0<=this.maxScrollY?0:this.maxScrollY;this.distX+=g;this.distY+=
d;this.absDistX=i.abs(this.distX);this.absDistY=i.abs(this.distY);6>this.absDistX&&6>this.absDistY||(this.options.lockDirection&&(this.absDistX>this.absDistY+5?(l=this.y,d=0):this.absDistY>this.absDistX+5&&(j=this.x,g=0)),this.moved=!0,this._pos(j,l),this.dirX=0<g?-1:0>g?1:0,this.dirY=0<d?-1:0>d?1:0,300<k-this.startTime&&(this.startTime=k,this.startX=this.x,this.startY=this.y),this.options.onScrollMove&&this.options.onScrollMove.call(this,b))},_end:function(b){if(!(f&&0!=b.touches.length)){var c=
f?b.changedTouches[0]:b,g,d,j={dist:0,time:0},l={dist:0,time:0},k=(b.timeStamp||Date.now())-this.startTime;g=this.x;d=this.y;this._unbind(t);this._unbind(v);this._unbind(x);this.options.onBeforeScrollEnd&&this.options.onBeforeScrollEnd.call(this,b);if(this.moved){if(300>k&&this.options.momentum){j=g?this._momentum(g-this.startX,k,-this.x,this.scrollerW-this.wrapperW+this.x,this.options.bounce?this.wrapperW:0):j;l=d?this._momentum(d-this.startY,k,-this.y,0>this.maxScrollY?this.scrollerH-this.wrapperH+
this.y:0,this.options.bounce?this.wrapperH:0):l;g=this.x+j.dist;d=this.y+l.dist;if(0<this.x&&0<g||this.x<this.maxScrollX&&g<this.maxScrollX)j={dist:0,time:0};if(0<this.y&&0<d||this.y<this.maxScrollY&&d<this.maxScrollY)l={dist:0,time:0}}j.dist||l.dist?(c=i.max(i.max(j.time,l.time),10),this.scrollTo(g>>0,d>>0,c)):this._resetPos(200)}else{if(f){for(g=c.target;1!=g.nodeType;)g=g.parentNode;"SELECT"!=g.tagName&&("INPUT"!=g.tagName&&"TEXTAREA"!=g.tagName)&&(d=document.createEvent("MouseEvents"),d.initMouseEvent("click",
!0,!0,b.view,1,c.screenX,c.screenY,c.clientX,c.clientY,b.ctrlKey,b.altKey,b.shiftKey,b.metaKey,0,null),d._fake=!0,g.dispatchEvent(d))}this._resetPos(200)}this.options.onTouchEnd&&this.options.onTouchEnd.call(this,b)}},_resetPos:function(b){var c=0<=this.x?0:this.x<this.maxScrollX?this.maxScrollX:this.x,f=0<=this.y||0<this.maxScrollY?0:this.y<this.maxScrollY?this.maxScrollY:this.y;c==this.x&&f==this.y?this.moved&&(this.options.onScrollEnd&&this.options.onScrollEnd.call(this),this.moved=!1):this.scrollTo(c,
f,b||0)},_mouseout:function(b){var c=b.relatedTarget;if(c)for(;c=c.parentNode;)if(c==this.wrapper)return;this._end(b)},_transitionEnd:function(b){b.target==this.scroller&&(this._unbind("webkitTransitionEnd"),this._startAni())},_startAni:function(){var b=this,c=b.x,f=b.y,d=Date.now(),g,j,l;b.animating||(b.steps.length?(g=b.steps.shift(),g.x==c&&g.y==f&&(g.time=0),b.animating=!0,b.moved=!0,b.options.useTransition)?(b._transitionTime(g.time),b._pos(g.x,g.y),b.animating=!1,g.time?b._bind("webkitTransitionEnd"):
b._resetPos(0)):(l=function(){var a=Date.now(),m;if(a>=d+g.time){b._pos(g.x,g.y);b.animating=false;b.options.onAnimationEnd&&b.options.onAnimationEnd.call(b);b._startAni()}else{a=(a-d)/g.time-1;j=i.sqrt(1-a*a);a=(g.x-c)*j+c;m=(g.y-f)*j+f;b._pos(a,m);if(b.animating)b.aniTime=C(l)}},l()):b._resetPos(400))},_transitionTime:function(b){this.scroller.style[o+"TransitionDuration"]=b+"ms"},_momentum:function(b,c,f,d,g){var c=i.abs(b)/c,j=c*c/0.0012;0<b&&j>f?(f+=g/(6/(6E-4*(j/c))),c=c*f/j,j=f):0>b&&j>d&&
(d+=g/(6/(6E-4*(j/c))),c=c*d/j,j=d);return{dist:j*(0>b?-1:1),time:c/6E-4>>0}},_offset:function(b){for(var c=-b.offsetLeft,f=-b.offsetTop;b=b.offsetParent;)c-=b.offsetLeft,f-=b.offsetTop;return{left:c,top:f}},_bind:function(b,c,f){(c||this.scroller).addEventListener(b,this,!!f)},_unbind:function(b,c,f){(c||this.scroller).removeEventListener(b,this,!!f)},destroy:function(){this.scroller.style[o+"Transform"]="";this._unbind(p,window);this._unbind(k);this._unbind(t);this._unbind(v);this._unbind(x);this._unbind("mouseout",
this.wrapper);this.options.useTransition&&this._unbind("webkitTransitionEnd");this.options.onDestroy&&this.options.onDestroy.call(this)},refresh:function(){var b;this.wrapperW=this.wrapper.clientWidth;this.wrapperH=this.wrapper.clientHeight;this.scrollerW=this.scroller.offsetWidth;this.scrollerH=this.scroller.offsetHeight;this.maxScrollX=this.wrapperW-this.scrollerW;this.maxScrollY=this.wrapperH-this.scrollerH;this.dirY=this.dirX=0;this.hScroll=this.options.hScroll&&0>this.maxScrollX;this.vScroll=
this.options.vScroll&&(!this.options.bounceLock&&!this.hScroll||this.scrollerH>this.wrapperH);b=this._offset(this.wrapper);this.wrapperOffsetLeft=-b.left;this.wrapperOffsetTop=-b.top;this.scroller.style[o+"TransitionDuration"]="0";this._resetPos(200)},scrollTo:function(b,c,f,d){var g=b;this.stop();g.length||(g=[{x:b,y:c,time:f,relative:d}]);b=0;for(c=g.length;b<c;b++)g[b].relative&&(g[b].x=this.x-g[b].x,g[b].y=this.y-g[b].y),this.steps.push({x:g[b].x,y:g[b].y,time:g[b].time||0});this._startAni()},
scrollToElement:function(b,c){var f;if(b=b.nodeType?b:this.scroller.querySelector(b))f=this._offset(b),f.left+=this.wrapperOffsetLeft,f.top+=this.wrapperOffsetTop,f.left=0<f.left?0:f.left<this.maxScrollX?this.maxScrollX:f.left,f.top=0<f.top?0:f.top<this.maxScrollY?this.maxScrollY:f.top,c=void 0===c?i.max(2*i.abs(f.left),2*i.abs(f.top)):c,this.scrollTo(f.left,f.top,c)},disable:function(){this.stop();this._resetPos(0);this.enabled=!1;this._unbind(t);this._unbind(v);this._unbind(x)},enable:function(){this.enabled=
!0},stop:function(){q(this.aniTime);this.steps=[];this.animating=this.moved=!1}};"undefined"!==typeof exports?exports.iScroll=n:window.iScroll=n})();
(function(){function i(h,a,e){if(h===a)return 0!==h||1/h==1/a;if(null==h||null==a)return h===a;h._chain&&(h=h._wrapped);a._chain&&(a=a._wrapped);if(h.isEqual&&d.isFunction(h.isEqual))return h.isEqual(a);if(a.isEqual&&d.isFunction(a.isEqual))return a.isEqual(h);var b=l.call(h);if(b!=l.call(a))return!1;switch(b){case "[object String]":return h==String(a);case "[object Number]":return h!=+h?a!=+a:0==h?1/h==1/a:h==+a;case "[object Date]":case "[object Boolean]":return+h==+a;case "[object RegExp]":return h.source==
a.source&&h.global==a.global&&h.multiline==a.multiline&&h.ignoreCase==a.ignoreCase}if("object"!=typeof h||"object"!=typeof a)return!1;for(var c=e.length;c--;)if(e[c]==h)return!0;e.push(h);var c=0,m=!0;if("[object Array]"==b){if(c=h.length,m=c==a.length)for(;c--&&(m=c in h==c in a&&i(h[c],a[c],e)););}else{if("constructor"in h!="constructor"in a||h.constructor!=a.constructor)return!1;for(var f in h)if(d.has(h,f)&&(c++,!(m=d.has(a,f)&&i(h[f],a[f],e))))break;if(m){for(f in a)if(d.has(a,f)&&!c--)break;
m=!c}}e.pop();return m}var o=this,n=o._,c={},g=Array.prototype,b=Object.prototype,f=g.slice,j=g.unshift,l=b.toString,C=b.hasOwnProperty,q=g.forEach,p=g.map,k=g.reduce,t=g.reduceRight,v=g.filter,x=g.every,w=g.some,E=g.indexOf,s=g.lastIndexOf,b=Array.isArray,G=Object.keys,K=Function.prototype.bind,d=function(h){return new r(h)};"undefined"!==typeof exports?("undefined"!==typeof module&&module.exports&&(exports=module.exports=d),exports._=d):o._=d;d.VERSION="1.3.3";var B=d.each=d.forEach=function(h,
a,e){if(h!=null)if(q&&h.forEach===q)h.forEach(a,e);else if(h.length===+h.length)for(var b=0,m=h.length;b<m;b++){if(b in h&&a.call(e,h[b],b,h)===c)break}else for(b in h)if(d.has(h,b)&&a.call(e,h[b],b,h)===c)break};d.map=d.collect=function(h,a,e){var b=[];if(h==null)return b;if(p&&h.map===p)return h.map(a,e);B(h,function(h,d,c){b[b.length]=a.call(e,h,d,c)});if(h.length===+h.length)b.length=h.length;return b};d.reduce=d.foldl=d.inject=function(h,a,e,b){var c=arguments.length>2;h==null&&(h=[]);if(k&&
h.reduce===k){b&&(a=d.bind(a,b));return c?h.reduce(a,e):h.reduce(a)}B(h,function(h,d,m){if(c)e=a.call(b,e,h,d,m);else{e=h;c=true}});if(!c)throw new TypeError("Reduce of empty array with no initial value");return e};d.reduceRight=d.foldr=function(a,b,e,c){var m=arguments.length>2;a==null&&(a=[]);if(t&&a.reduceRight===t){c&&(b=d.bind(b,c));return m?a.reduceRight(b,e):a.reduceRight(b)}var f=d.toArray(a).reverse();c&&!m&&(b=d.bind(b,c));return m?d.reduce(f,b,e,c):d.reduce(f,b)};d.find=d.detect=function(a,
b,e){var d;L(a,function(a,h,c){if(b.call(e,a,h,c)){d=a;return true}});return d};d.filter=d.select=function(a,b,e){var d=[];if(a==null)return d;if(v&&a.filter===v)return a.filter(b,e);B(a,function(a,h,c){b.call(e,a,h,c)&&(d[d.length]=a)});return d};d.reject=function(a,b,e){var d=[];if(a==null)return d;B(a,function(a,h,c){b.call(e,a,h,c)||(d[d.length]=a)});return d};d.every=d.all=function(a,b,e){var d=true;if(a==null)return d;if(x&&a.every===x)return a.every(b,e);B(a,function(a,h,m){if(!(d=d&&b.call(e,
a,h,m)))return c});return!!d};var L=d.some=d.any=function(a,b,e){b||(b=d.identity);var m=false;if(a==null)return m;if(w&&a.some===w)return a.some(b,e);B(a,function(a,h,d){if(m||(m=b.call(e,a,h,d)))return c});return!!m};d.include=d.contains=function(a,b){var e=false;if(a==null)return e;if(E&&a.indexOf===E)return a.indexOf(b)!=-1;return e=L(a,function(a){return a===b})};d.invoke=function(a,b){var e=f.call(arguments,2);return d.map(a,function(a){return(d.isFunction(b)?b||a:a[b]).apply(a,e)})};d.pluck=
function(a,b){return d.map(a,function(a){return a[b]})};d.max=function(a,b,e){if(!b&&d.isArray(a)&&a[0]===+a[0])return Math.max.apply(Math,a);if(!b&&d.isEmpty(a))return-Infinity;var c={computed:-Infinity};B(a,function(a,h,d){h=b?b.call(e,a,h,d):a;h>=c.computed&&(c={value:a,computed:h})});return c.value};d.min=function(a,b,e){if(!b&&d.isArray(a)&&a[0]===+a[0])return Math.min.apply(Math,a);if(!b&&d.isEmpty(a))return Infinity;var c={computed:Infinity};B(a,function(a,h,d){h=b?b.call(e,a,h,d):a;h<c.computed&&
(c={value:a,computed:h})});return c.value};d.shuffle=function(a){var b=[],e;B(a,function(a,h){e=Math.floor(Math.random()*(h+1));b[h]=b[e];b[e]=a});return b};d.sortBy=function(a,b,e){var c=d.isFunction(b)?b:function(a){return a[b]};return d.pluck(d.map(a,function(a,h,b){return{value:a,criteria:c.call(e,a,h,b)}}).sort(function(a,h){var b=a.criteria,e=h.criteria;return b===void 0?1:e===void 0?-1:b<e?-1:b>e?1:0}),"value")};d.groupBy=function(a,b){var e={},c=d.isFunction(b)?b:function(a){return a[b]};
B(a,function(a,b){var h=c(a,b);(e[h]||(e[h]=[])).push(a)});return e};d.sortedIndex=function(a,b,e){e||(e=d.identity);for(var c=0,m=a.length;c<m;){var f=c+m>>1;e(a[f])<e(b)?c=f+1:m=f}return c};d.toArray=function(a){return!a?[]:d.isArray(a)||d.isArguments(a)?f.call(a):a.toArray&&d.isFunction(a.toArray)?a.toArray():d.values(a)};d.size=function(a){return d.isArray(a)?a.length:d.keys(a).length};d.first=d.head=d.take=function(a,b,e){return b!=null&&!e?f.call(a,0,b):a[0]};d.initial=function(a,b,e){return f.call(a,
0,a.length-(b==null||e?1:b))};d.last=function(a,b,e){return b!=null&&!e?f.call(a,Math.max(a.length-b,0)):a[a.length-1]};d.rest=d.tail=function(a,b,e){return f.call(a,b==null||e?1:b)};d.compact=function(a){return d.filter(a,function(a){return!!a})};d.flatten=function(a,b){return d.reduce(a,function(a,h){if(d.isArray(h))return a.concat(b?h:d.flatten(h));a[a.length]=h;return a},[])};d.without=function(a){return d.difference(a,f.call(arguments,1))};d.uniq=d.unique=function(a,b,e){var e=e?d.map(a,e):a,
c=[];a.length<3&&(b=true);d.reduce(e,function(e,m,f){if(b?d.last(e)!==m||!e.length:!d.include(e,m)){e.push(m);c.push(a[f])}return e},[]);return c};d.union=function(){return d.uniq(d.flatten(arguments,true))};d.intersection=d.intersect=function(a){var b=f.call(arguments,1);return d.filter(d.uniq(a),function(a){return d.every(b,function(b){return d.indexOf(b,a)>=0})})};d.difference=function(a){var b=d.flatten(f.call(arguments,1),true);return d.filter(a,function(a){return!d.include(b,a)})};d.zip=function(){for(var a=
f.call(arguments),b=d.max(d.pluck(a,"length")),e=Array(b),c=0;c<b;c++)e[c]=d.pluck(a,""+c);return e};d.indexOf=function(a,b,e){if(a==null)return-1;var c;if(e){e=d.sortedIndex(a,b);return a[e]===b?e:-1}if(E&&a.indexOf===E)return a.indexOf(b);e=0;for(c=a.length;e<c;e++)if(e in a&&a[e]===b)return e;return-1};d.lastIndexOf=function(a,b){if(a==null)return-1;if(s&&a.lastIndexOf===s)return a.lastIndexOf(b);for(var e=a.length;e--;)if(e in a&&a[e]===b)return e;return-1};d.range=function(a,b,e){if(arguments.length<=
1){b=a||0;a=0}for(var e=arguments[2]||1,c=Math.max(Math.ceil((b-a)/e),0),d=0,m=Array(c);d<c;){m[d++]=a;a=a+e}return m};var H=function(){};d.bind=function(a,b){var e,c;if(a.bind===K&&K)return K.apply(a,f.call(arguments,1));if(!d.isFunction(a))throw new TypeError;c=f.call(arguments,2);return e=function(){if(!(this instanceof e))return a.apply(b,c.concat(f.call(arguments)));H.prototype=a.prototype;var d=new H,m=a.apply(d,c.concat(f.call(arguments)));return Object(m)===m?m:d}};d.bindAll=function(a){var b=
f.call(arguments,1);b.length==0&&(b=d.functions(a));B(b,function(b){a[b]=d.bind(a[b],a)});return a};d.memoize=function(a,b){var e={};b||(b=d.identity);return function(){var c=b.apply(this,arguments);return d.has(e,c)?e[c]:e[c]=a.apply(this,arguments)}};d.delay=function(a,b){var e=f.call(arguments,2);return setTimeout(function(){return a.apply(null,e)},b)};d.defer=function(a){return d.delay.apply(d,[a,1].concat(f.call(arguments,1)))};d.throttle=function(a,b){var e,c,m,f,g,y,j=d.debounce(function(){g=
f=false},b);return function(){e=this;c=arguments;m||(m=setTimeout(function(){m=null;g&&a.apply(e,c);j()},b));f?g=true:y=a.apply(e,c);j();f=true;return y}};d.debounce=function(a,b,e){var c;return function(){var d=this,m=arguments;e&&!c&&a.apply(d,m);clearTimeout(c);c=setTimeout(function(){c=null;e||a.apply(d,m)},b)}};d.once=function(a){var b=false,e;return function(){if(b)return e;b=true;return e=a.apply(this,arguments)}};d.wrap=function(a,b){return function(){var e=[a].concat(f.call(arguments,0));
return b.apply(this,e)}};d.compose=function(){var a=arguments;return function(){for(var b=arguments,e=a.length-1;e>=0;e--)b=[a[e].apply(this,b)];return b[0]}};d.after=function(a,b){return a<=0?b():function(){if(--a<1)return b.apply(this,arguments)}};d.keys=G||function(a){if(a!==Object(a))throw new TypeError("Invalid object");var b=[],e;for(e in a)d.has(a,e)&&(b[b.length]=e);return b};d.values=function(a){return d.map(a,d.identity)};d.functions=d.methods=function(a){var b=[],e;for(e in a)d.isFunction(a[e])&&
b.push(e);return b.sort()};d.extend=function(a){B(f.call(arguments,1),function(b){for(var e in b)a[e]=b[e]});return a};d.pick=function(a){var b={};B(d.flatten(f.call(arguments,1)),function(e){e in a&&(b[e]=a[e])});return b};d.defaults=function(a){B(f.call(arguments,1),function(b){for(var e in b)a[e]==null&&(a[e]=b[e])});return a};d.clone=function(a){return!d.isObject(a)?a:d.isArray(a)?a.slice():d.extend({},a)};d.tap=function(a,b){b(a);return a};d.isEqual=function(a,b){return i(a,b,[])};d.isEmpty=
function(a){if(a==null)return true;if(d.isArray(a)||d.isString(a))return a.length===0;for(var b in a)if(d.has(a,b))return false;return true};d.isElement=function(a){return!!(a&&a.nodeType==1)};d.isArray=b||function(a){return l.call(a)=="[object Array]"};d.isObject=function(a){return a===Object(a)};d.isArguments=function(a){return l.call(a)=="[object Arguments]"};d.isArguments(arguments)||(d.isArguments=function(a){return!(!a||!d.has(a,"callee"))});d.isFunction=function(a){return l.call(a)=="[object Function]"};
d.isString=function(a){return l.call(a)=="[object String]"};d.isNumber=function(a){return l.call(a)=="[object Number]"};d.isFinite=function(a){return d.isNumber(a)&&isFinite(a)};d.isNaN=function(a){return a!==a};d.isBoolean=function(a){return a===true||a===false||l.call(a)=="[object Boolean]"};d.isDate=function(a){return l.call(a)=="[object Date]"};d.isRegExp=function(a){return l.call(a)=="[object RegExp]"};d.isNull=function(a){return a===null};d.isUndefined=function(a){return a===void 0};d.has=function(a,
b){return C.call(a,b)};d.noConflict=function(){o._=n;return this};d.identity=function(a){return a};d.times=function(a,b,e){for(var c=0;c<a;c++)b.call(e,c)};d.escape=function(a){return(""+a).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&#x27;").replace(/\//g,"&#x2F;")};d.result=function(a,b){if(a==null)return null;var e=a[b];return d.isFunction(e)?e.call(a):e};d.mixin=function(a){B(d.functions(a),function(b){var e=d[b]=a[b];r.prototype[b]=function(){var a=
f.call(arguments);j.call(a,this._wrapped);return F(e.apply(d,a),this._chain)}})};var a=0;d.uniqueId=function(b){var c=a++;return b?b+c:c};d.templateSettings={evaluate:/<%([\s\S]+?)%>/g,interpolate:/<%=([\s\S]+?)%>/g,escape:/<%-([\s\S]+?)%>/g};var m=/.^/,y={"\\":"\\","'":"'",r:"\r",n:"\n",t:"\t",u2028:"\u2028",u2029:"\u2029"},M;for(M in y)y[y[M]]=M;var O=/\\|'|\r|\n|\t|\u2028|\u2029/g,z=/\\(\\|'|r|n|t|u2028|u2029)/g,I=function(a){return a.replace(z,function(a,b){return y[b]})};d.template=function(a,
b,e){e=d.defaults(e||{},d.templateSettings);a="__p+='"+a.replace(O,function(a){return"\\"+y[a]}).replace(e.escape||m,function(a,b){return"'+\n_.escape("+I(b)+")+\n'"}).replace(e.interpolate||m,function(a,b){return"'+\n("+I(b)+")+\n'"}).replace(e.evaluate||m,function(a,b){return"';\n"+I(b)+"\n;__p+='"})+"';\n";e.variable||(a="with(obj||{}){\n"+a+"}\n");var a="var __p='';var print=function(){__p+=Array.prototype.join.call(arguments, '')};\n"+a+"return __p;\n",c=new Function(e.variable||"obj","_",a);
if(b)return c(b,d);b=function(a){return c.call(this,a,d)};b.source="function("+(e.variable||"obj")+"){\n"+a+"}";return b};d.chain=function(a){return d(a).chain()};var r=function(a){this._wrapped=a};d.prototype=r.prototype;var F=function(a,b){return b?d(a).chain():a};d.mixin(d);B("pop push reverse shift sort splice unshift".split(" "),function(a){var b=g[a];r.prototype[a]=function(){var e=this._wrapped;b.apply(e,arguments);var c=e.length;(a=="shift"||a=="splice")&&c===0&&delete e[0];return F(e,this._chain)}});
B(["concat","join","slice"],function(a){var b=g[a];r.prototype[a]=function(){return F(b.apply(this._wrapped,arguments),this._chain)}});r.prototype.chain=function(){this._chain=true;return this};r.prototype.value=function(){return this._wrapped}}).call(this);
(function(){var i=this,o=i.Backbone,n=Array.prototype.slice,c=Array.prototype.splice,g;g="undefined"!==typeof exports?exports:i.Backbone={};g.VERSION="0.9.2";var b=i._;!b&&"undefined"!==typeof require&&(b=require("underscore"));var f=i.jQuery||i.Zepto||i.ender;g.setDomLibrary=function(a){f=a};g.noConflict=function(){i.Backbone=o;return this};g.emulateHTTP=!1;g.emulateJSON=!1;var j=/\s+/,l=g.Events={on:function(a,b,c){var d,f,g,l,i;if(!b)return this;a=a.split(j);for(d=this._callbacks||(this._callbacks=
{});f=a.shift();)g=(i=d[f])?i.tail:{},g.next=l={},g.context=c,g.callback=b,d[f]={tail:l,next:i?i.next:g};return this},off:function(a,c,d){var f,g,l,i,k,n;if(g=this._callbacks){if(!a&&!c&&!d)return delete this._callbacks,this;for(a=a?a.split(j):b.keys(g);f=a.shift();)if(l=g[f],delete g[f],l&&(c||d))for(i=l.tail;(l=l.next)!==i;)if(k=l.callback,n=l.context,c&&k!==c||d&&n!==d)this.on(f,k,n);return this}},trigger:function(a){var b,c,d,f,g,l;if(!(d=this._callbacks))return this;g=d.all;a=a.split(j);for(l=
n.call(arguments,1);b=a.shift();){if(c=d[b])for(f=c.tail;(c=c.next)!==f;)c.callback.apply(c.context||this,l);if(c=g){f=c.tail;for(b=[b].concat(l);(c=c.next)!==f;)c.callback.apply(c.context||this,b)}}return this}};l.bind=l.on;l.unbind=l.off;var C=g.Model=function(a,c){var d;a||(a={});c&&c.parse&&(a=this.parse(a));if(d=L(this,"defaults"))a=b.extend({},d,a);c&&c.collection&&(this.collection=c.collection);this.attributes={};this._escapedAttributes={};this.cid=b.uniqueId("c");this.changed={};this._silent=
{};this._pending={};this.set(a,{silent:!0});this.changed={};this._silent={};this._pending={};this._previousAttributes=b.clone(this.attributes);this.initialize.apply(this,arguments)};b.extend(C.prototype,l,{changed:null,_silent:null,_pending:null,idAttribute:"id",initialize:function(){},toJSON:function(){return b.clone(this.attributes)},get:function(a){return this.attributes[a]},escape:function(a){var c;if(c=this._escapedAttributes[a])return c;c=this.get(a);return this._escapedAttributes[a]=b.escape(null==
c?"":""+c)},has:function(a){return null!=this.get(a)},set:function(a,c,d){var f,g;b.isObject(a)||null==a?(f=a,d=c):(f={},f[a]=c);d||(d={});if(!f)return this;f instanceof C&&(f=f.attributes);if(d.unset)for(g in f)f[g]=void 0;if(!this._validate(f,d))return!1;this.idAttribute in f&&(this.id=f[this.idAttribute]);var c=d.changes={},j=this.attributes,l=this._escapedAttributes,i=this._previousAttributes||{};for(g in f){a=f[g];if(!b.isEqual(j[g],a)||d.unset&&b.has(j,g))delete l[g],(d.silent?this._silent:
c)[g]=!0;d.unset?delete j[g]:j[g]=a;!b.isEqual(i[g],a)||b.has(j,g)!=b.has(i,g)?(this.changed[g]=a,d.silent||(this._pending[g]=!0)):(delete this.changed[g],delete this._pending[g])}d.silent||this.change(d);return this},unset:function(a,b){(b||(b={})).unset=!0;return this.set(a,null,b)},clear:function(a){(a||(a={})).unset=!0;return this.set(b.clone(this.attributes),a)},fetch:function(a){var a=a?b.clone(a):{},c=this,d=a.success;a.success=function(b,f,g){if(!c.set(c.parse(b,g),a))return!1;d&&d(c,b)};
a.error=g.wrapError(a.error,c,a);return(this.sync||g.sync).call(this,"read",this,a)},save:function(a,c,d){var f,j;b.isObject(a)||null==a?(f=a,d=c):(f={},f[a]=c);d=d?b.clone(d):{};if(d.wait){if(!this._validate(f,d))return!1;j=b.clone(this.attributes)}a=b.extend({},d,{silent:!0});if(f&&!this.set(f,d.wait?a:d))return!1;var l=this,i=d.success;d.success=function(a,c,h){c=l.parse(a,h);if(d.wait){delete d.wait;c=b.extend(f||{},c)}if(!l.set(c,d))return false;i?i(l,a):l.trigger("sync",l,a,d)};d.error=g.wrapError(d.error,
l,d);c=this.isNew()?"create":"update";c=(this.sync||g.sync).call(this,c,this,d);d.wait&&this.set(j,a);return c},destroy:function(a){var a=a?b.clone(a):{},c=this,d=a.success,f=function(){c.trigger("destroy",c,c.collection,a)};if(this.isNew())return f(),!1;a.success=function(b){a.wait&&f();d?d(c,b):c.trigger("sync",c,b,a)};a.error=g.wrapError(a.error,c,a);var j=(this.sync||g.sync).call(this,"delete",this,a);a.wait||f();return j},url:function(){var a=L(this,"urlRoot")||L(this.collection,"url")||H();
return this.isNew()?a:a+("/"==a.charAt(a.length-1)?"":"/")+encodeURIComponent(this.id)},parse:function(a){return a},clone:function(){return new this.constructor(this.attributes)},isNew:function(){return null==this.id},change:function(a){a||(a={});var c=this._changing;this._changing=!0;for(var d in this._silent)this._pending[d]=!0;var f=b.extend({},a.changes,this._silent);this._silent={};for(d in f)this.trigger("change:"+d,this,this.get(d),a);if(c)return this;for(;!b.isEmpty(this._pending);){this._pending=
{};this.trigger("change",this,a);for(d in this.changed)!this._pending[d]&&!this._silent[d]&&delete this.changed[d];this._previousAttributes=b.clone(this.attributes)}this._changing=!1;return this},hasChanged:function(a){return!arguments.length?!b.isEmpty(this.changed):b.has(this.changed,a)},changedAttributes:function(a){if(!a)return this.hasChanged()?b.clone(this.changed):!1;var c,d=!1,f=this._previousAttributes,g;for(g in a)if(!b.isEqual(f[g],c=a[g]))(d||(d={}))[g]=c;return d},previous:function(a){return!arguments.length||
!this._previousAttributes?null:this._previousAttributes[a]},previousAttributes:function(){return b.clone(this._previousAttributes)},isValid:function(){return!this.validate(this.attributes)},_validate:function(a,c){if(c.silent||!this.validate)return!0;var a=b.extend({},this.attributes,a),d=this.validate(a,c);if(!d)return!0;c&&c.error?c.error(this,d,c):this.trigger("error",this,d,c);return!1}});var q=g.Collection=function(a,b){b||(b={});b.model&&(this.model=b.model);b.comparator&&(this.comparator=b.comparator);
this._reset();this.initialize.apply(this,arguments);a&&this.reset(a,{silent:!0,parse:b.parse})};b.extend(q.prototype,l,{model:C,initialize:function(){},toJSON:function(a){return this.map(function(b){return b.toJSON(a)})},add:function(a,d){var f,g,j,l,i,k={},n={},h=[];d||(d={});a=b.isArray(a)?a.slice():[a];f=0;for(g=a.length;f<g;f++){if(!(j=a[f]=this._prepareModel(a[f],d)))throw Error("Can't add an invalid model to a collection");l=j.cid;i=j.id;k[l]||this._byCid[l]||null!=i&&(n[i]||this._byId[i])?
h.push(f):k[l]=n[i]=j}for(f=h.length;f--;)a.splice(h[f],1);f=0;for(g=a.length;f<g;f++)(j=a[f]).on("all",this._onModelEvent,this),this._byCid[j.cid]=j,null!=j.id&&(this._byId[j.id]=j);this.length+=g;c.apply(this.models,[null!=d.at?d.at:this.models.length,0].concat(a));this.comparator&&this.sort({silent:!0});if(d.silent)return this;f=0;for(g=this.models.length;f<g;f++)if(k[(j=this.models[f]).cid])d.index=f,j.trigger("add",j,this,d);return this},remove:function(a,c){var d,f,g,j;c||(c={});a=b.isArray(a)?
a.slice():[a];d=0;for(f=a.length;d<f;d++)if(j=this.getByCid(a[d])||this.get(a[d]))delete this._byId[j.id],delete this._byCid[j.cid],g=this.indexOf(j),this.models.splice(g,1),this.length--,c.silent||(c.index=g,j.trigger("remove",j,this,c)),this._removeReference(j);return this},push:function(a,b){a=this._prepareModel(a,b);this.add(a,b);return a},pop:function(a){var b=this.at(this.length-1);this.remove(b,a);return b},unshift:function(a,c){a=this._prepareModel(a,c);this.add(a,b.extend({at:0},c));return a},
shift:function(a){var b=this.at(0);this.remove(b,a);return b},get:function(a){return null==a?void 0:this._byId[null!=a.id?a.id:a]},getByCid:function(a){return a&&this._byCid[a.cid||a]},at:function(a){return this.models[a]},where:function(a){return b.isEmpty(a)?[]:this.filter(function(b){for(var c in a)if(a[c]!==b.get(c))return!1;return!0})},sort:function(a){a||(a={});if(!this.comparator)throw Error("Cannot sort a set without a comparator");var c=b.bind(this.comparator,this);1==this.comparator.length?
this.models=this.sortBy(c):this.models.sort(c);a.silent||this.trigger("reset",this,a);return this},pluck:function(a){return b.map(this.models,function(b){return b.get(a)})},reset:function(a,c){a||(a=[]);c||(c={});for(var d=0,f=this.models.length;d<f;d++)this._removeReference(this.models[d]);this._reset();this.add(a,b.extend({silent:!0},c));c.silent||this.trigger("reset",this,c);return this},fetch:function(a){a=a?b.clone(a):{};void 0===a.parse&&(a.parse=!0);var c=this,d=a.success;a.success=function(b,
f,g){c[a.add?"add":"reset"](c.parse(b,g),a);d&&d(c,b)};a.error=g.wrapError(a.error,c,a);return(this.sync||g.sync).call(this,"read",this,a)},create:function(a,c){var d=this,c=c?b.clone(c):{},a=this._prepareModel(a,c);if(!a)return!1;c.wait||d.add(a,c);var f=c.success;c.success=function(b,g){c.wait&&d.add(b,c);f?f(b,g):b.trigger("sync",a,g,c)};a.save(null,c);return a},parse:function(a){return a},chain:function(){return b(this.models).chain()},_reset:function(){this.length=0;this.models=[];this._byId=
{};this._byCid={}},_prepareModel:function(a,b){b||(b={});a instanceof C?a.collection||(a.collection=this):(b.collection=this,a=new this.model(a,b),a._validate(a.attributes,b)||(a=!1));return a},_removeReference:function(a){this==a.collection&&delete a.collection;a.off("all",this._onModelEvent,this)},_onModelEvent:function(a,b,c,d){("add"==a||"remove"==a)&&c!=this||("destroy"==a&&this.remove(b,d),b&&a==="change:"+b.idAttribute&&(delete this._byId[b.previous(b.idAttribute)],this._byId[b.id]=b),this.trigger.apply(this,
arguments))}});b.each("forEach each map reduce reduceRight find detect filter select reject every all some any include contains invoke max min sortBy sortedIndex toArray size first initial rest last without indexOf shuffle lastIndexOf isEmpty groupBy".split(" "),function(a){q.prototype[a]=function(){return b[a].apply(b,[this.models].concat(b.toArray(arguments)))}});var p=g.Router=function(a){a||(a={});a.routes&&(this.routes=a.routes);this._bindRoutes();this.initialize.apply(this,arguments)},k=/:\w+/g,
t=/\*\w+/g,v=/[-[\]{}()+?.,\\^$|#\s]/g;b.extend(p.prototype,l,{initialize:function(){},route:function(a,c,d){g.history||(g.history=new x);b.isRegExp(a)||(a=this._routeToRegExp(a));d||(d=this[c]);g.history.route(a,b.bind(function(b){b=this._extractParameters(a,b);d&&d.apply(this,b);this.trigger.apply(this,["route:"+c].concat(b));g.history.trigger("route",this,c,b)},this));return this},navigate:function(a,b){g.history.navigate(a,b)},_bindRoutes:function(){if(this.routes){var a=[],b;for(b in this.routes)a.unshift([b,
this.routes[b]]);b=0;for(var c=a.length;b<c;b++)this.route(a[b][0],a[b][1],this[a[b][1]])}},_routeToRegExp:function(a){a=a.replace(v,"\\$&").replace(k,"([^/]+)").replace(t,"(.*?)");return RegExp("^"+a+"$")},_extractParameters:function(a,b){return a.exec(b).slice(1)}});var x=g.History=function(){this.handlers=[];b.bindAll(this,"checkUrl")},w=/^[#\/]/,E=/msie [\w.]+/;x.started=!1;b.extend(x.prototype,l,{interval:50,getHash:function(a){return(a=(a?a.location:window.location).href.match(/#(.*)$/))?a[1]:
""},getFragment:function(a,b){if(null==a)if(this._hasPushState||b){var a=window.location.pathname,c=window.location.search;c&&(a+=c)}else a=this.getHash();a.indexOf(this.options.root)||(a=a.substr(this.options.root.length));return a.replace(w,"")},start:function(a){if(x.started)throw Error("Backbone.history has already been started");x.started=!0;this.options=b.extend({},{root:"/"},this.options,a);this._wantsHashChange=!1!==this.options.hashChange;this._wantsPushState=!!this.options.pushState;this._hasPushState=
!(!this.options.pushState||!window.history||!window.history.pushState);var a=this.getFragment(),c=document.documentMode;if(c=E.exec(navigator.userAgent.toLowerCase())&&(!c||7>=c))this.iframe=f('<iframe src="javascript:0" tabindex="-1" />').hide().appendTo("body")[0].contentWindow,this.navigate(a);this._hasPushState?f(window).bind("popstate",this.checkUrl):this._wantsHashChange&&"onhashchange"in window&&!c?f(window).bind("hashchange",this.checkUrl):this._wantsHashChange&&(this._checkUrlInterval=setInterval(this.checkUrl,
this.interval));this.fragment=a;a=window.location;c=a.pathname==this.options.root;if(this._wantsHashChange&&this._wantsPushState&&!this._hasPushState&&!c)return this.fragment=this.getFragment(null,!0),window.location.replace(this.options.root+"#"+this.fragment),!0;this._wantsPushState&&(this._hasPushState&&c&&a.hash)&&(this.fragment=this.getHash().replace(w,""),window.history.replaceState({},document.title,a.protocol+"//"+a.host+this.options.root+this.fragment));if(!this.options.silent)return this.loadUrl()},
stop:function(){f(window).unbind("popstate",this.checkUrl).unbind("hashchange",this.checkUrl);clearInterval(this._checkUrlInterval);x.started=!1},route:function(a,b){this.handlers.unshift({route:a,callback:b})},checkUrl:function(){var a=this.getFragment();a==this.fragment&&this.iframe&&(a=this.getFragment(this.getHash(this.iframe)));if(a==this.fragment)return!1;this.iframe&&this.navigate(a);this.loadUrl()||this.loadUrl(this.getHash())},loadUrl:function(a){var c=this.fragment=this.getFragment(a);return b.any(this.handlers,
function(a){if(a.route.test(c))return a.callback(c),!0})},navigate:function(a,b){if(!x.started)return!1;if(!b||!0===b)b={trigger:b};var c=(a||"").replace(w,"");this.fragment!=c&&(this._hasPushState?(0!=c.indexOf(this.options.root)&&(c=this.options.root+c),this.fragment=c,window.history[b.replace?"replaceState":"pushState"]({},document.title,c)):this._wantsHashChange?(this.fragment=c,this._updateHash(window.location,c,b.replace),this.iframe&&c!=this.getFragment(this.getHash(this.iframe))&&(b.replace||
this.iframe.document.open().close(),this._updateHash(this.iframe.location,c,b.replace))):window.location.assign(this.options.root+a),b.trigger&&this.loadUrl(a))},_updateHash:function(a,b,c){c?a.replace(a.toString().replace(/(javascript:|#).*$/,"")+"#"+b):a.hash=b}});var s=g.View=function(a){this.cid=b.uniqueId("view");this._configure(a||{});this._ensureElement();this.initialize.apply(this,arguments);this.delegateEvents()},G=/^(\S+)\s*(.*)$/,K="model collection el id attributes className tagName".split(" ");
b.extend(s.prototype,l,{tagName:"div",$:function(a){return this.$el.find(a)},initialize:function(){},render:function(){return this},remove:function(){this.$el.remove();return this},make:function(a,b,c){a=document.createElement(a);b&&f(a).attr(b);c&&f(a).html(c);return a},setElement:function(a,b){this.$el&&this.undelegateEvents();this.$el=a instanceof f?a:f(a);this.el=this.$el[0];!1!==b&&this.delegateEvents();return this},delegateEvents:function(a){if(a||(a=L(this,"events"))){this.undelegateEvents();
for(var c in a){var d=a[c];b.isFunction(d)||(d=this[a[c]]);if(!d)throw Error('Method "'+a[c]+'" does not exist');var f=c.match(G),g=f[1],f=f[2],d=b.bind(d,this),g=g+(".delegateEvents"+this.cid);""===f?this.$el.bind(g,d):this.$el.delegate(f,g,d)}}},undelegateEvents:function(){this.$el.unbind(".delegateEvents"+this.cid)},_configure:function(a){this.options&&(a=b.extend({},this.options,a));for(var c=0,d=K.length;c<d;c++){var f=K[c];a[f]&&(this[f]=a[f])}this.options=a},_ensureElement:function(){if(this.el)this.setElement(this.el,
!1);else{var a=L(this,"attributes")||{};this.id&&(a.id=this.id);this.className&&(a["class"]=this.className);this.setElement(this.make(this.tagName,a),!1)}}});C.extend=q.extend=p.extend=s.extend=function(a,c){var d=this,f;f=a&&a.hasOwnProperty("constructor")?a.constructor:function(){d.apply(this,arguments)};b.extend(f,d);B.prototype=d.prototype;f.prototype=new B;a&&b.extend(f.prototype,a);c&&b.extend(f,c);f.prototype.constructor=f;f.__super__=d.prototype;f.extend=this.extend;return f};var d={create:"POST",
update:"PUT","delete":"DELETE",read:"GET"};g.sync=function(a,c,j){var l=d[a];j||(j={});var i={type:l,dataType:"json"};j.url||(i.url=L(c,"url")||H());if(!j.data&&c&&("create"==a||"update"==a))i.contentType="application/json",i.data=JSON.stringify(c.toJSON());g.emulateJSON&&(i.contentType="application/x-www-form-urlencoded",i.data=i.data?{model:i.data}:{});if(g.emulateHTTP&&("PUT"===l||"DELETE"===l))g.emulateJSON&&(i.data._method=l),i.type="POST",i.beforeSend=function(a){a.setRequestHeader("X-HTTP-Method-Override",
l)};"GET"!==i.type&&!g.emulateJSON&&(i.processData=!1);return f.ajax(b.extend(i,j))};g.wrapError=function(a,b,c){return function(d,f){f=d===b?f:d;a?a(b,f,c):b.trigger("error",b,f,c)}};var B=function(){},L=function(a,c){return!a||!a[c]?null:b.isFunction(a[c])?a[c]():a[c]},H=function(){throw Error('A "url" property or function must be specified');}}).call(this);var requirejs,require,define;
(function(i){function o(a){return"[object Function]"===E.call(a)}function n(a){return"[object Array]"===E.call(a)}function c(a,b){if(a){var c;for(c=0;c<a.length&&(!a[c]||!b(a[c],c,a));c+=1);}}function g(a,b){if(a){var c;for(c=a.length-1;-1<c&&(!a[c]||!b(a[c],c,a));c-=1);}}function b(a,b){for(var c in a)if(a.hasOwnProperty(c)&&b(a[c],c))break}function f(a,c,d,e){c&&b(c,function(b,c){if(d||!a.hasOwnProperty(c))e&&"string"!==typeof b?(a[c]||(a[c]={}),f(a[c],b,d,e)):a[c]=b});return a}function j(a,b){return function(){return b.apply(a,
arguments)}}function l(a){if(!a)return a;var b=i;c(a.split("."),function(a){b=b[a]});return b}function C(a,b,c){return function(){var d=G.call(arguments,0),e;if(c&&o(e=d[d.length-1]))e.__requireJsBuild=!0;d.push(b);return a.apply(null,d)}}function q(a,b,d){c([["toUrl"],["undef"],["defined","requireDefined"],["specified","requireSpecified"]],function(c){var e=c[1]||c[0];a[c[0]]=b?C(b[e],d):function(){var a=m[H];return a[e].apply(a,arguments)}})}function p(a,b,c,d){b=Error(b+"\nhttp://requirejs.org/docs/errors.html#"+
a);b.requireType=a;b.requireModules=d;c&&(b.originalError=c);return b}function k(e){function g(a,b,c){var d=b&&b.split("/"),e=d,f=A.map,h=f&&f["*"],j,l,i;if(a&&"."===a.charAt(0))if(b){e=A.pkgs[b]?d=[b]:d.slice(0,d.length-1);b=a=e.concat(a.split("/"));for(e=0;b[e];e+=1)if(j=b[e],"."===j)b.splice(e,1),e-=1;else if(".."===j)if(1===e&&(".."===b[2]||".."===b[0]))break;else 0<e&&(b.splice(e-1,2),e-=2);e=A.pkgs[b=a[0]];a=a.join("/");e&&a===b+"/"+e.main&&(a=b)}else 0===a.indexOf("./")&&(a=a.substring(2));
if(c&&(d||h)&&f){b=a.split("/");for(e=b.length;0<e;e-=1){l=b.slice(0,e).join("/");if(d)for(j=d.length;0<j;j-=1)if(c=f[d.slice(0,j).join("/")])if(c=c[l]){i=c;break}!i&&(h&&h[l])&&(i=h[l]);if(i){b.splice(0,e,i);a=b.join("/");break}}}return a}function h(a){d&&c(document.getElementsByTagName("script"),function(b){if(b.getAttribute("data-requiremodule")===a&&b.getAttribute("data-requirecontext")===u.contextName)return b.parentNode.removeChild(b),!0})}function k(a){var b=A.paths[a];if(b&&n(b)&&1<b.length)return h(a),
b.shift(),u.undef(a),u.require([a]),!0}function m(a,b,c,d){var e=a?a.indexOf("!"):-1,f=null,h=b?b.name:null,j=a,l=!0,i="",k,n;a||(l=!1,a="_@r"+(R+=1));-1!==e&&(f=a.substring(0,e),a=a.substring(e+1,a.length));f&&(f=g(f,h,d),n=J[f]);a&&(f?i=n&&n.normalize?n.normalize(a,function(a){return g(a,h,d)}):g(a,h,d):(i=g(a,h,d),k=u.nameToUrl(i)));a=f&&!n&&!c?"_unnormalized"+(aa+=1):"";return{prefix:f,name:i,parentMap:b,unnormalized:!!a,url:k,originalName:j,isDefine:l,id:(f?f+"!"+i:i)+a}}function s(a){var b=
a.id,c=D[b];c||(c=D[b]=new u.Module(a));return c}function t(a,b,c){var d=a.id,e=D[d];if(J.hasOwnProperty(d)&&(!e||e.defineEmitComplete))"defined"===b&&c(J[d]);else s(a).on(b,c)}function r(a,b){var d=a.requireModules,e=!1;if(b)b(a);else if(c(d,function(b){if(b=D[b])b.error=a,b.events.error&&(e=!0,b.emit("error",a))}),!e)z.onError(a)}function v(){M.length&&(K.apply(P,[P.length-1,0].concat(M)),M=[])}function y(a,b,c){a=a&&a.map;b=C(c||u.require,a,b);q(b,u,a);b.isBrowser=d;return b}function E(a){delete D[a];
c(S,function(b,c){if(b.map.id===a)return S.splice(c,1),b.defined||(u.waitCount-=1),!0})}function F(a,b){var d=a.map.id,e=a.depMaps,g;if(a.inited){if(b[d])return a;b[d]=!0;c(e,function(a){if(a=D[a.id])return!a.inited||!a.enabled?(g=null,delete b[d],!0):g=F(a,f({},b))});return g}}function G(a,b,d){var e=a.map.id,f=a.depMaps;if(a.inited&&a.map.isDefine){if(b[e])return J[e];b[e]=a;c(f,function(c){var c=c.id,f=D[c];!T[c]&&f&&(!f.inited||!f.enabled?d[e]=!0:(f=G(f,b,d),d[c]||a.defineDepById(c,f)))});a.check(!0);
return J[e]}}function I(a){a.check()}function H(){var a=1E3*A.waitSeconds,e=a&&u.startTime+a<(new Date).getTime(),f=[],g=!1,j=!0,l,i,m;if(!V){V=!0;b(D,function(a){l=a.map;i=l.id;if(a.enabled&&!a.error)if(!a.inited&&e)k(i)?g=m=!0:(f.push(i),h(i));else if(!a.inited&&(a.fetched&&l.isDefine)&&(g=!0,!l.prefix))return j=!1});if(e&&f.length)return a=p("timeout","Load timeout for modules: "+f,null,f),a.contextName=u.contextName,r(a);j&&(c(S,function(a){if(!a.defined){var a=F(a,{}),c={};a&&(G(a,c,{}),b(c,
I))}}),b(D,I));if((!e||m)&&g)if((d||B)&&!W)W=setTimeout(function(){W=0;H()},50);V=!1}}function X(a){s(m(a[0],null,!0)).init(a[1],a[2])}function Q(b){var b=b.currentTarget||b.srcElement,c=u.onScriptLoad;b.detachEvent&&!a?b.detachEvent("onreadystatechange",c):b.removeEventListener("load",c,!1);c=u.onScriptError;(!b.detachEvent||a)&&b.removeEventListener("error",c,!1);return{node:b,id:b&&b.getAttribute("data-requiremodule")}}var A={waitSeconds:7,baseUrl:"./",paths:{},pkgs:{},shim:{}},D={},Y={},P=[],
J={},U={},R=1,aa=1,S=[],V,Z,u,T,W;T={require:function(a){return y(a)},exports:function(a){a.usingExports=!0;if(a.map.isDefine)return a.exports=J[a.map.id]={}},module:function(a){return a.module={id:a.map.id,uri:a.map.url,config:function(){return A.config&&A.config[a.map.id]||{}},exports:J[a.map.id]}}};Z=function(a){this.events=Y[a.id]||{};this.map=a;this.shim=A.shim[a.id];this.depExports=[];this.depMaps=[];this.depMatched=[];this.pluginMaps={};this.depCount=0};Z.prototype={init:function(a,b,c,d){d=
d||{};if(!this.inited){this.factory=b;if(c)this.on("error",c);else this.events.error&&(c=j(this,function(a){this.emit("error",a)}));this.depMaps=a&&a.slice(0);this.depMaps.rjsSkipMap=a.rjsSkipMap;this.errback=c;this.inited=!0;this.ignore=d.ignore;d.enabled||this.enabled?this.enable():this.check()}},defineDepById:function(a,b){var d;c(this.depMaps,function(b,c){if(b.id===a)return d=c,!0});return this.defineDep(d,b)},defineDep:function(a,b){this.depMatched[a]||(this.depMatched[a]=!0,this.depCount-=
1,this.depExports[a]=b)},fetch:function(){if(!this.fetched){this.fetched=!0;u.startTime=(new Date).getTime();var a=this.map;if(this.shim)y(this,!0)(this.shim.deps||[],j(this,function(){return a.prefix?this.callPlugin():this.load()}));else return a.prefix?this.callPlugin():this.load()}},load:function(){var a=this.map.url;U[a]||(U[a]=!0,u.load(this.map.id,a))},check:function(a){if(this.enabled&&!this.enabling){var b=this.map.id,c=this.depExports,d=this.exports,e=this.factory,f;if(this.inited)if(this.error)this.emit("error",
this.error);else{if(!this.defining){this.defining=!0;if(1>this.depCount&&!this.defined){if(o(e)){if(this.events.error)try{d=u.execCb(b,e,c,d)}catch(g){f=g}else d=u.execCb(b,e,c,d);this.map.isDefine&&((c=this.module)&&void 0!==c.exports&&c.exports!==this.exports?d=c.exports:void 0===d&&this.usingExports&&(d=this.exports));if(f)return f.requireMap=this.map,f.requireModules=[this.map.id],f.requireType="define",r(this.error=f)}else d=e;this.exports=d;if(this.map.isDefine&&!this.ignore&&(J[b]=d,z.onResourceLoad))z.onResourceLoad(u,
this.map,this.depMaps);delete D[b];this.defined=!0;u.waitCount-=1;0===u.waitCount&&(S=[])}this.defining=!1;!a&&(this.defined&&!this.defineEmitted)&&(this.defineEmitted=!0,this.emit("defined",this.exports),this.defineEmitComplete=!0)}}else this.fetch()}},callPlugin:function(){var a=this.map,c=a.id,d=m(a.prefix,null,!1,!0);t(d,"defined",j(this,function(d){var e=this.map.name,f=this.map.parentMap?this.map.parentMap.name:null;if(this.map.unnormalized){if(d.normalize&&(e=d.normalize(e,function(a){return g(a,
f,!0)})||""),d=m(a.prefix+"!"+e,this.map.parentMap,!1,!0),t(d,"defined",j(this,function(a){this.init([],function(){return a},null,{enabled:!0,ignore:!0})})),d=D[d.id]){if(this.events.error)d.on("error",j(this,function(a){this.emit("error",a)}));d.enable()}}else e=j(this,function(a){this.init([],function(){return a},null,{enabled:!0})}),e.error=j(this,function(a){this.inited=!0;this.error=a;a.requireModules=[c];b(D,function(a){0===a.map.id.indexOf(c+"_unnormalized")&&E(a.map.id)});r(a)}),e.fromText=
function(a,b){var c=O;c&&(O=!1);s(m(a));z.exec(b);c&&(O=!0);u.completeLoad(a)},d.load(a.name,y(a.parentMap,!0,function(a,b){a.rjsSkipMap=true;return u.require(a,b)}),e,A)}));u.enable(d,this);this.pluginMaps[d.id]=d},enable:function(){this.enabled=!0;this.waitPushed||(S.push(this),u.waitCount+=1,this.waitPushed=!0);this.enabling=!0;c(this.depMaps,j(this,function(a,b){var c,d;if(typeof a==="string"){a=m(a,this.map.isDefine?this.map:this.map.parentMap,false,!this.depMaps.rjsSkipMap);this.depMaps[b]=
a;if(c=T[a.id]){this.depExports[b]=c(this);return}this.depCount=this.depCount+1;t(a,"defined",j(this,function(a){this.defineDep(b,a);this.check()}));this.errback&&t(a,"error",this.errback)}c=a.id;d=D[c];!T[c]&&(d&&!d.enabled)&&u.enable(a,this)}));b(this.pluginMaps,j(this,function(a){var b=D[a.id];b&&!b.enabled&&u.enable(a,this)}));this.enabling=!1;this.check()},on:function(a,b){var c=this.events[a];c||(c=this.events[a]=[]);c.push(b)},emit:function(a,b){c(this.events[a],function(a){a(b)});"error"===
a&&delete this.events[a]}};return u={config:A,contextName:e,registry:D,defined:J,urlFetched:U,waitCount:0,defQueue:P,Module:Z,makeModuleMap:m,configure:function(a){a.baseUrl&&"/"!==a.baseUrl.charAt(a.baseUrl.length-1)&&(a.baseUrl+="/");var d=A.pkgs,e=A.shim,g=A.paths,h=A.map;f(A,a,!0);A.paths=f(g,a.paths,!0);a.map&&(A.map=f(h||{},a.map,!0,!0));a.shim&&(b(a.shim,function(a,b){n(a)&&(a={deps:a});if(a.exports&&!a.exports.__buildReady)a.exports=u.makeShimExports(a.exports);e[b]=a}),A.shim=e);a.packages&&
(c(a.packages,function(a){a=typeof a==="string"?{name:a}:a;d[a.name]={name:a.name,location:a.location||a.name,main:(a.main||"main").replace(w,"").replace(x,"")}}),A.pkgs=d);b(D,function(a,b){a.map=m(b)});if(a.deps||a.callback)u.require(a.deps||[],a.callback)},makeShimExports:function(a){var b;return"string"===typeof a?(b=function(){return l(a)},b.exports=a,b):function(){return a.apply(i,arguments)}},requireDefined:function(a,b){var c=m(a,b,!1,!0).id;return J.hasOwnProperty(c)},requireSpecified:function(a,
b){a=m(a,b,!1,!0).id;return J.hasOwnProperty(a)||D.hasOwnProperty(a)},require:function(a,b,c,d){var f;if("string"===typeof a){if(o(b))return r(p("requireargs","Invalid require call"),c);if(z.get)return z.get(u,a,b);a=m(a,b,!1,!0);a=a.id;return!J.hasOwnProperty(a)?r(p("notloaded",'Module name "'+a+'" has not been loaded yet for context: '+e)):J[a]}c&&!o(c)&&(d=c,c=void 0);b&&!o(b)&&(d=b,b=void 0);for(v();P.length;){f=P.shift();if(null===f[0])return r(p("mismatch","Mismatched anonymous define() module: "+
f[f.length-1]));X(f)}s(m(null,d)).init(a,b,c,{enabled:!0});H();return u.require},undef:function(a){var b=m(a,null,!0),c=D[a];delete J[a];delete U[b.url];delete Y[a];c&&(c.events.defined&&(Y[a]=c.events),E(a))},enable:function(a){D[a.id]&&s(a).enable()},completeLoad:function(a){var b=A.shim[a]||{},c=b.exports&&b.exports.exports,d,e;for(v();P.length;){e=P.shift();if(null===e[0]){e[0]=a;if(d)break;d=!0}else e[0]===a&&(d=!0);X(e)}e=D[a];if(!d&&!J[a]&&e&&!e.inited){if(A.enforceDefine&&(!c||!l(c)))return k(a)?
void 0:r(p("nodefine","No define call for "+a,null,[a]));X([a,b.deps||[],b.exports])}H()},toUrl:function(a,b){var c=a.lastIndexOf("."),d=null;-1!==c&&(d=a.substring(c,a.length),a=a.substring(0,c));return u.nameToUrl(g(a,b&&b.id,!0),d)},nameToUrl:function(a,b){var c,d,e,f,g,h;if(z.jsExtRegExp.test(a))f=a+(b||"");else{c=A.paths;d=A.pkgs;f=a.split("/");for(g=f.length;0<g;g-=1)if(h=f.slice(0,g).join("/"),e=d[h],h=c[h]){n(h)&&(h=h[0]);f.splice(0,g,h);break}else if(e){c=a===e.name?e.location+"/"+e.main:
e.location;f.splice(0,g,c);break}f=f.join("/")+(b||".js");f=("/"===f.charAt(0)||f.match(/^[\w\+\.\-]+:/)?"":A.baseUrl)+f}return A.urlArgs?f+((-1===f.indexOf("?")?"?":"&")+A.urlArgs):f},load:function(a,b){z.load(u,a,b)},execCb:function(a,b,c,d){return b.apply(d,c)},onScriptLoad:function(a){if("load"===a.type||L.test((a.currentTarget||a.srcElement).readyState))N=null,a=Q(a),u.completeLoad(a.id)},onScriptError:function(a){var b=Q(a);if(!k(b.id))return r(p("scripterror","Script error",a,[b.id]))}}}var t=
/(\/\*([\s\S]*?)\*\/|([^:]|^)\/\/(.*)$)/mg,v=/[^.]\s*require\s*\(\s*["']([^'"\s]+)["']\s*\)/g,x=/\.js$/,w=/^\.\//,E=Object.prototype.toString,s=Array.prototype,G=s.slice,K=s.splice,d=!!("undefined"!==typeof window&&navigator&&document),B=!d&&"undefined"!==typeof importScripts,L=d&&"PLAYSTATION 3"===navigator.platform?/^complete$/:/^(complete|loaded)$/,H="_",a="undefined"!==typeof opera&&"[object Opera]"===opera.toString(),m={},y={},M=[],O=!1,z,I,r,F,h,N,e,Q,R;if("undefined"===typeof define){if("undefined"!==
typeof requirejs){if(o(requirejs))return;y=requirejs;requirejs=void 0}"undefined"!==typeof require&&!o(require)&&(y=require,require=void 0);z=requirejs=function(a,b,c,d){var e=H,f;if(!n(a)&&typeof a!=="string"){f=a;if(n(b)){a=b;b=c;c=d}else a=[]}if(f&&f.context)e=f.context;(d=m[e])||(d=m[e]=z.s.newContext(e));f&&d.configure(f);return d.require(a,b,c)};z.config=function(a){return z(a)};require||(require=z);z.version="2.0.4";z.jsExtRegExp=/^\/|:|\?|\.js$/;z.isBrowser=d;s=z.s={contexts:m,newContext:k};
z({});q(z);if(d&&(I=s.head=document.getElementsByTagName("head")[0],r=document.getElementsByTagName("base")[0]))I=s.head=r.parentNode;z.onError=function(a){throw a;};z.load=function(b,c,f){var g=b&&b.config||{},h;if(d){h=g.xhtml?document.createElementNS("http://www.w3.org/1999/xhtml","html:script"):document.createElement("script");h.type=g.scriptType||"text/javascript";h.charset="utf-8";h.async=true;h.setAttribute("data-requirecontext",b.contextName);h.setAttribute("data-requiremodule",c);if(h.attachEvent&&
!(h.attachEvent.toString&&h.attachEvent.toString().indexOf("[native code")<0)&&!a){O=true;h.attachEvent("onreadystatechange",b.onScriptLoad)}else{h.addEventListener("load",b.onScriptLoad,false);h.addEventListener("error",b.onScriptError,false)}h.src=f;e=h;r?I.insertBefore(h,r):I.appendChild(h);e=null;return h}if(B){importScripts(f);b.completeLoad(c)}};d&&g(document.getElementsByTagName("script"),function(a){if(!I)I=a.parentNode;if(F=a.getAttribute("data-main")){if(!y.baseUrl){h=F.split("/");Q=h.pop();
R=h.length?h.join("/")+"/":"./";y.baseUrl=R;F=Q}F=F.replace(x,"");y.deps=y.deps?y.deps.concat(F):[F];return true}});define=function(a,b,c){var d,f;if(typeof a!=="string"){c=b;b=a;a=null}if(!n(b)){c=b;b=[]}if(!b.length&&o(c)&&c.length){c.toString().replace(t,"").replace(v,function(a,c){b.push(c)});b=(c.length===1?["require"]:["require","exports","module"]).concat(b)}if(O){if(!(d=e)){N&&N.readyState==="interactive"||g(document.getElementsByTagName("script"),function(a){if(a.readyState==="interactive")return N=
a});d=N}if(d){a||(a=d.getAttribute("data-requiremodule"));f=m[d.getAttribute("data-requirecontext")]}}(f?f.defQueue:M).push([a,b,c])};define.amd={jQuery:!0};z.exec=function(a){return eval(a)};z(y)}})(this);define("requireLib",function(){});var __slice=[].slice;
define("cell",[],function(){var i,o,n,c,g,b,f,j;b=function(){};n="function"===typeof("undefined"!==typeof console&&null!==console?console.error:void 0)?function(){var b;b=1<=arguments.length?__slice.call(arguments,0):[];return console.error.apply(console,b)}:function(){};i=this.$;c=this.document||{createElement:function(){}};f=c.createRange();j=function(b,f){for(var g,j;0<f.length;)if(null!=(g=f.shift()))_.isElement(g)?b.appendChild(g):g.jquery?g.appendTo(b):"string"===(j=typeof g)||"number"===j?
b.appendChild(c.createTextNode(g)):_.isArray(g)?Array.prototype.unshift.apply(f,g):n("render_el: unsupported render element",g);return b};i(c).ready(function(){f.selectNode(c.body);i("[data-cell]").each(function(){var b,c=this;(b=this.getAttribute("data-cell"))&&require(["cell!"+b],function(b){c.appendChild((new b).render().el)})})});return g={Cell:o=Backbone.View.extend({render:function(){this.el.innerHTML="";j(this.el,[this.render_el()]);this.after_render();return this}}),pluginBuilder:"cell-builder-plugin",
load:function(f,j,q){j([f],function(p){var k;if("object"!==typeof p)n("cell!: Couldn't load "+f+" cell. cell definitions should be objects, but instead was "+typeof p);else{if(null==(null!=(k=g.__preinstalledCells__)?k[f]:void 0))(g.__preinstalledCells__||(g.__preinstalledCells__={}))[f]=!0,k=c.createElement("link"),k.href=j.toUrl(""+f+".css"),k.rel="stylesheet",k.type="text/css",i("head")[0].appendChild(k);p.className=p.name=/(.*\/)?(.*)$/.exec(f)[2];p.render_el||(p.render_el=b);p.after_render||
(p.after_render=b);q(o.extend(p))}})}}});__slice=[].slice;
define("__",["cell"],function(i){var o,n,c,g,b,f;o=i.Cell;n="function"===typeof("undefined"!==typeof console&&null!==console?console.error:void 0)?function(){var b;b=1<=arguments.length?__slice.call(arguments,0):[];return console.error.apply(console,b)}:function(){};g=function(b){return(null!=b?b.constructor:void 0)===Object};f=function(b,c){for(var f,g;0<c.length;)if(null!=(f=c.shift()))_.isElement(f)?b.appendChild(f):f.jquery?f.appendTo(b):"string"===(g=typeof f)||"number"===g?b.appendChild(document.createTextNode(f)):
_.isArray(f)?Array.prototype.unshift.apply(c,f):n("__: unsupported render child",f);return b};b=function(b){var c;if(b=/^(\w+)?(#([\w\-]+))*(\.[\w\.\-]+)?$/.exec(b))return{tag:b[1]||"div",id:b[3],className:(c=b[4])?c.slice(1).replace(/\./g," "):""}};c=function(){var c,i,C,q,p,k,t,v,x,w;c=arguments[0];i=arguments[1];p=3<=arguments.length?__slice.call(arguments,2):[];if(c)return _.isElement(i)&&(p.unshift(i),i=void 0),(x=function(){if(typeof c==="string"){if(t=b(c)){k=document.createElement(t.tag);
t.id&&k.setAttribute("id",t.id);if(i!=null)if(g(i))for(v in i){w=i[v];v!=="class"?k.setAttribute(v,w):k.className=k.className+w}else p.unshift(i);if(t.className)k.className=k.className+(k.className?" "+t.className:t.className);return k}return n("__(): unsupported argument '"+c+"'")}if(c.prototype instanceof o){if(q=typeof i==="string"&&(t=b(i))?g(p[0])?((C=p.shift()).id=t.id,C.className=t.className,C):{id:t.id,className:t.className}:g(i)?i:void 0)q.className=q.className?""+c.prototype.className+" "+
q.className:c.prototype.className;return(new c(q)).render().el}return _.isElement(c)?c:n("__(): unsupported argument "+c)}())&&f(x,p)};c.$=function(){var b;b=1<=arguments.length?__slice.call(arguments,0):[];return $(c.apply(null,b))};return c});define("Config",[],function(){return{default_tab:"recipes"}});
define("cell-mobile/Nav",["Config"],function(i){var o,n,c,g;g=0;c=function(){return 100*Date.now()+g++%100};n=function(b){return""+b+"Page"};_.extend((o=function(){}).prototype,Backbone.Events,{_uid_to_location:{},_tab_histories:{},_isnt_first:!1,_loading_uid:void 0,_tab_history:function(b){var c;return(c=this._tab_histories)[b]||(c[b]=[])},_set_location:function(b,c){var g;if(!this._loading_uid)return this._isnt_first=!0,this._loading_uid=b.uid,g=this.location,this.trigger("change:location",this.location=
b,g,c),this._syncLocation()},_syncLocation:function(){var b;b=this.location;return Backbone.history.navigate("#"+b.tab+"/"+b.uid+"/"+b.page+"?"+encodeURIComponent(JSON.stringify(b.data)))},_go_back_to:function(b){var c,g,i,n,o,p;if(!this._loading_uid&&this._isnt_first&&(g=null!=(c=this._uid_to_location[b])?c.tab:void 0)){p=i=this._tab_history(g);c=n=0;for(o=p.length;n<o;c=++n)if(g=p[c],g.uid===b){n=i.splice(c+1);c=0;for(i=n.length;c<i;c++)b=n[c],this._uid_to_location[b.uid]=void 0;this._set_location(g,
{is_back:!0,is_switch_tab:g.tab!==this.location.tab});return!0}}return!1},go_to_referrer:function(b){var c;if(this._uid_to_location[b=null!=(c=this._uid_to_location[b])?c._referrer_uid:void 0])return this._go_back_to(b)},switch_tab:function(b){var f,g;this._loading_uid||(g=this._tab_history(b),(f=g.length)?b=g[f-1]:(g.push(b={uid:c(),tab:b,page:n(b),data:{},has_referrer:!1}),this._uid_to_location[b.uid]=b),this._set_location(b,{is_back:!1,is_switch_tab:!0}))},go_to:function(b){var f,g,i,n,o;i=b.tab;
g=b.page;f=b.data;if(!this._loading_uid){if(null==g)throw"no page specified";b=this._isnt_first;i||(i=this.location.tab);if(b&&i!==this.location.tab)throw"Trying to go to another tab.  Use switch_tab instead.";n=this._tab_history(i);n.push(g={uid:c(),tab:i,page:g,data:f||{},has_referrer:null!=this.location,_referrer_uid:null!=(o=this.location)?o.uid:void 0});(this._uid_to_location[g.uid]=g)&&this._set_location(g,{is_back:!1,is_switch_tab:!b})}},start:function(b){var c,g=this;b(function(b){if(null!=
b&&g._loading_uid===b)return g._loading_uid=void 0});c=this;new (Backbone.Router.extend({initialize:function(){this.route(/.*/,"404",function(){return c.switch_tab(i.default_tab)});this.route(/(\w+)(\/(\d+))?(\/(\w+))?(\?(.*))?/,"tab_salt_page_pagedata",function(b,g,i,j,k,o,v){if(!i||!c._go_back_to(Number(i)))return c.go_to({tab:b,page:k||n(b),data:v&&JSON.parse(decodeURIComponent(v))})})}}));Backbone.history.start()}});return new o});
define("cell-mobile/views/PageViewModel",[],function(){var i,o;o={};i=function(i){this.location=i.location;return this.title="Loading..."};i.for_location=function(n){var c;if(null!=(null!=n?n.uid:void 0))return o[c=n.uid]||(o[c]=new i({location:n}))};_.extend(i.prototype,Backbone.Events,{set_title:function(i){var c;if(this.title!==i)return c=this.title,this.title=i,this.trigger("change:title",this.title,c)}});return i});
define("cell-mobile/views/PageTitleBar",["__","cell-mobile/Nav","./PageViewModel"],function(i,o,n){return{render_el:function(){return[this.options.location.has_referrer?i(".backbutton","Back",i(".actual","Back")):void 0,this.$title=i.$(".title")]},after_render:function(){var c=this;return n.for_location(this.options.location).on("change:title",function(g){return c.$title.html(g)})},events:{"tap .backbutton":function(){return o.go_to_referrer(this.options.location.uid)}}}});
define("cell-mobile/views/TitleBar",["__","cell-mobile/Nav","cell!./PageTitleBar"],function(i,o,n){return{after_render:function(){var c=this;return o.on("change:location",function(g,b,f){var i;i=f.is_back;if(f.is_switch_tab)return b&&c.$tab(b.tab).removeClass("active"),c.$tab(g.tab).addClass("active"),c.$page_title_bar(g).addClass("active").removeClass("slide-out-fade slide-out-fade-reverse slide-in-fade slide-in-fade-reverse");b&&c.$page_title_bar(b).removeClass("active slide-in-fade slide-in-fade-reverse").addClass("slide-out-fade"+
(i&&"-reverse"||""));return c.$page_title_bar(g).removeClass("slide-out-fade slide-out-fade-reverse").addClass("active slide-in-fade"+(i&&"-reverse"||""))})},$page_title_bar:function(c){var g;g=this.$el.children(".tab[data-tab='"+c.tab+"']").children(".PageTitleBar[data-location-uid='"+c.uid+"']");return g[0]?g:i.$(n,{location:c}).attr("data-location-uid",c.uid).appendTo(this.$tab(c.tab))},$tab:function(c){var g;return(g=this.$el.children(".tab[data-tab='"+c+"']"))[0]?g:i.$(".tab",{"data-tab":c}).appendTo(this.$el)},
events:{"webkitAnimationEnd .tab > .PageTitleBar.slide-out-fade,.PageTitleBar.slide-out-fade-reverse":function(c){return $(c.target).removeClass("slide-out-fade slide-out-fade-reverse")},"webkitAnimationEnd .tab > .PageTitleBar.slide-out-fade-reverse":function(c){return $(c.target).remove()}}}});
define("cell-mobile/views/PageContainer",["require","__","cell-mobile/Nav","./PageViewModel"],function(i,o,n,c){var g,b;b={};g=function(c){return b[c]};setInterval(function(){var b,c;return null!=(b=g(null!=(c=n.location)?c.uid:void 0))?b.refresh_scroller():void 0},500);n.on("change:location",function(b,c){var i;if(c)return null!=(i=g(c.uid))?i.stop_scrolling():void 0});return{initialize:function(){this._prev_height=this._prev_container_height=-1;return b[this.options.location.uid]=this},after_render:function(){var b,
g=this;b=this.options.location;return i(["cell!views/pages/"+(b.page[0].toUpperCase()+b.page.slice(1))],function(i){g.$el.append(g.$page=o.$(i,".page.active",{model:c.for_location(b)}));return g.scroller=new iScroll(g.el)})},stop_scrolling:function(){var b;return null!=(b=this.scroller)?b.scrollTo(0,0,0,!0):void 0},refresh_scroller:function(){var b,c,g,i;b=this.$el.height();c=(null!=(g=this.$page)?g.height():void 0)||0;if(b!==this._prev_container_height||c!==this._prev_height)return this._prev_container_height=
b,this._prev_height=c,null!=(i=this.scroller)?i.refresh():void 0}}});
define("cell-mobile/views/Content",["__","cell-mobile/Nav","cell!./PageContainer"],function(i,o,n){return{after_render:function(){var c=this;return o.on("change:location",function(g,b,f){var i;i=f.is_back;if(f.is_switch_tab)return b&&c.$tab(b.tab).removeClass("active"),c.$tab(g.tab).addClass("active"),c.$page(g).addClass("active").removeClass("page-slide-out page-slide-out-reverse page-slide-in page-slide-in-reverse"),c.options.location_uid_loaded(g.uid);b&&c.$page(b).removeClass("active page-slide-in page-slide-in-reverse").addClass("page-slide-out"+
(i&&"-reverse"||""));return c.$page(g).removeClass("page-slide-out page-slide-out-reverse").addClass("active page-slide-in"+(i&&"-reverse"||""))})},$page:function(c){var g;g=this.$el.children(".tab[data-tab='"+c.tab+"']").children(".PageContainer[data-location-uid='"+c.uid+"']");return g[0]?g:i.$(n,{location:c}).attr("data-location-uid",c.uid).appendTo(this.$tab(c.tab))},$tab:function(c){var g;return(g=this.$el.children(".tab[data-tab='"+c+"']"))[0]?g:i.$(".tab",{"data-tab":c}).appendTo(this.$el)},
events:{"webkitAnimationEnd .tab > .PageContainer.active":function(c){return this.options.location_uid_loaded(Number($(c.target).data("location-uid")))},"webkitAnimationEnd .tab > .PageContainer.page-slide-out,.PageContainer.page-slide-out-reverse":function(c){return $(c.target).removeClass("page-slide-out page-slide-out-reverse")},"webkitAnimationEnd .tab > .PageContainer.page-slide-out-reverse":function(c){return $(c.target).remove()}}}});
define("cell-mobile/views/TabBar",["__","cell-mobile/Nav"],function(i,o){var n;n={recipes:"Recipes",calendar:"Calendar",pantry:"Pantry",groceries:"Groceries"};return{tagName:"ul",render_el:function(){var c,g,b;b=[];for(g in n)c=n[g],b.push(i("li.tab",{"data-tab":g},i(".tab-label",c)));return b},after_render:function(){var c=this;return o.on("change:location",function(g,b,f){if(f.is_switch_tab)return c.$("li.active").removeClass("active"),c.$("li[data-tab="+g.tab+"]").addClass("active")})},events:{"tap li.tab":function(c){return o.switch_tab($(c.target).closest("li.tab").data("tab"))}}}});
require(["cell"],function(i){i.__preinstalledCells__={"cell-mobile/views/App":0,"cell-mobile/views/TitleBar":0,"cell-mobile/views/PageTitleBar":0,"cell-mobile/views/Content":0,"cell-mobile/views/PageContainer":0,"cell-mobile/views/TabBar":0,"views/pages/RecipesPage":0}});
define("views/pages/RecipesPage",["__","cell-mobile/Nav"],function(i,o){return{initialize:function(){return this.model.set_title("Recipes")},render_el:function(){var n,c,g;g=[];for(n=c=0;100>=c;n=++c)g.push(i("a.recipe",{"data-recipeid":n},"Recipe #"+n));return g},events:{"tap a.recipe":function(i){if(null!=(i=$(i.target).closest("a.recipe").data("recipeid")))return o.go_to({page:"RecipePage",data:{id:i}})}}}});define("Preloads",["cell!views/pages/RecipesPage"],function(){});var hideAddressBar;
document.addEventListener("touchmove",function(i){return i.preventDefault()});hideAddressBar=function(){var i;i=function(){return window.scrollTo(0,1)};setTimeout(i,500);return $(window).bind("resize",i)};$(document.body).toggleClass(navigator.userAgent.match(/iP(od|ad|hone)/i)?window.navigator.standalone?"IOSFullScreen":(hideAddressBar(),"IOS"):(hideAddressBar(),"ANDROID"),!0);
define("cell-mobile/views/App","__ cell-mobile/Nav cell!./TitleBar cell!./Content cell!./TabBar Preloads".split(" "),function(i,o,n,c,g){return{render_el:function(){var b=this;return[i(n),i(c,{location_uid_loaded:function(c){return b._done_loading_location_uid(c)}}),i(g)]},after_render:function(){var b=this;return o.start(function(c){b._done_loading_location_uid=c})}}});
