/*
 RequireJS 1.0.5 Copyright (c) 2010-2012, The Dojo Foundation All Rights Reserved.
 Available via the MIT or new BSD license.
 see: http://github.com/jrburke/requirejs for details
*/
(function(){var e=Math,d=/webkit/i.test(navigator.appVersion)?"webkit":/firefox/i.test(navigator.userAgent)?"Moz":"opera"in window?"O":"",i="WebKitCSSMatrix"in window&&"m11"in new WebKitCSSMatrix,g="ontouchstart"in window,m=d+"Transform"in document.documentElement.style,b=/iphone|ipad/gi.test(navigator.appVersion),k=/playbook/gi.test(navigator.appVersion),h=b||k,o=function(){return window.requestAnimationFrame||window.webkitRequestAnimationFrame||window.mozRequestAnimationFrame||window.oRequestAnimationFrame||
window.msRequestAnimationFrame||function(a){return setTimeout(a,17)}}(),p=window.cancelRequestAnimationFrame||window.webkitCancelRequestAnimationFrame||window.mozCancelRequestAnimationFrame||window.oCancelRequestAnimationFrame||window.msCancelRequestAnimationFrame||clearTimeout,c="onorientationchange"in window?"orientationchange":"resize",j=g?"touchstart":"mousedown",u=g?"touchmove":"mousemove",r=g?"touchend":"mouseup",x=g?"touchcancel":"mouseup",w="translate"+(i?"3d(":"("),s=i?",0)":")",i=function(a,
q){var f;this.wrapper="object"==typeof a?a:document.getElementById(a);this.wrapper.style.overflow="hidden";this.scroller=this.wrapper.children[0];this.options={hScroll:!0,vScroll:!0,x:0,y:0,bounce:!0,bounceLock:!1,momentum:!0,lockDirection:!0,useTransform:!0,useTransition:!1,onRefresh:null,onBeforeScrollStart:function(a){a.preventDefault()},onScrollStart:null,onBeforeScrollMove:null,onScrollMove:null,onBeforeScrollEnd:null,onScrollEnd:null,onTouchEnd:null,onDestroy:null};for(f in q)this.options[f]=
q[f];this.x=this.options.x;this.y=this.options.y;this.options.useTransform=m?this.options.useTransform:!1;this.options.hScrollbar=this.options.hScroll&&this.options.hScrollbar;this.options.vScrollbar=this.options.vScroll&&this.options.vScrollbar;this.options.useTransition=h&&this.options.useTransition;this.scroller.style[d+"TransitionProperty"]=this.options.useTransform?"-"+d.toLowerCase()+"-transform":"top left";this.scroller.style[d+"TransitionDuration"]="0";this.scroller.style[d+"TransformOrigin"]=
"0 0";this.options.useTransition&&(this.scroller.style[d+"TransitionTimingFunction"]="cubic-bezier(0.33,0.66,0.66,1)");this.options.useTransform?this.scroller.style[d+"Transform"]=w+this.x+"px,"+this.y+"px"+s:this.scroller.style.cssText+=";position:absolute;top:"+this.y+"px;left:"+this.x+"px";this.refresh();this._bind(c,window);this._bind(j);g||this._bind("mouseout",this.wrapper)};i.prototype={enabled:!0,x:0,y:0,steps:[],scale:1,handleEvent:function(a){switch(a.type){case j:if(!g&&0!==a.button)break;
this._start(a);break;case u:this._move(a);break;case r:case x:this._end(a);break;case c:this._resize();break;case "mouseout":this._mouseout(a);break;case "webkitTransitionEnd":this._transitionEnd(a)}},_resize:function(){this.refresh()},_pos:function(a,q){a=this.hScroll?a:0;q=this.vScroll?q:0;this.options.useTransform?this.scroller.style[d+"Transform"]=w+a+"px,"+q+"px"+s+" scale("+this.scale+")":(a=e.round(a),q=e.round(q),this.scroller.style.left=a+"px",this.scroller.style.top=q+"px");this.x=a;this.y=
q},_start:function(a){var q=g?a.touches[0]:a,f,c;if(this.enabled){this.options.onBeforeScrollStart&&this.options.onBeforeScrollStart.call(this,a);this.options.useTransition&&this._transitionTime(0);this.zoomed=this.animating=this.moved=!1;this.dirY=this.dirX=this.absDistY=this.absDistX=this.distY=this.distX=0;if(this.options.momentum&&(this.options.useTransform?(f=getComputedStyle(this.scroller,null)[d+"Transform"].replace(/[^0-9-.,]/g,"").split(","),c=1*f[4],f=1*f[5]):(c=1*getComputedStyle(this.scroller,
null).left.replace(/[^0-9-]/g,""),f=1*getComputedStyle(this.scroller,null).top.replace(/[^0-9-]/g,"")),c!=this.x||f!=this.y))this.options.useTransition?this._unbind("webkitTransitionEnd"):p(this.aniTime),this.steps=[],this._pos(c,f);this.absStartX=this.x;this.absStartY=this.y;this.startX=this.x;this.startY=this.y;this.pointX=q.pageX;this.pointY=q.pageY;this.startTime=a.timeStamp||Date.now();this.options.onScrollStart&&this.options.onScrollStart.call(this,a);this._bind(u);this._bind(r);this._bind(x)}},
_move:function(a){var q=g?a.touches[0]:a,f=q.pageX-this.pointX,c=q.pageY-this.pointY,h=this.x+f,b=this.y+c,j=a.timeStamp||Date.now();this.options.onBeforeScrollMove&&this.options.onBeforeScrollMove.call(this,a);this.pointX=q.pageX;this.pointY=q.pageY;if(0<h||h<this.maxScrollX)h=this.options.bounce?this.x+f/2:0<=h||0<=this.maxScrollX?0:this.maxScrollX;if(0<b||b<this.maxScrollY)b=this.options.bounce?this.y+c/2:0<=b||0<=this.maxScrollY?0:this.maxScrollY;if(6>this.absDistX&&6>this.absDistY)this.distX+=
f,this.distY+=c,this.absDistX=e.abs(this.distX),this.absDistY=e.abs(this.distY);else{if(this.options.lockDirection)if(this.absDistX>this.absDistY+5)b=this.y,c=0;else if(this.absDistY>this.absDistX+5)h=this.x,f=0;this.moved=!0;this._pos(h,b);this.dirX=0<f?-1:0>f?1:0;this.dirY=0<c?-1:0>c?1:0;if(300<j-this.startTime)this.startTime=j,this.startX=this.x,this.startY=this.y;this.options.onScrollMove&&this.options.onScrollMove.call(this,a)}},_end:function(a){if(!(g&&0!=a.touches.length)){var q=g?a.changedTouches[0]:
a,f,c,h={dist:0,time:0},b={dist:0,time:0},j=(a.timeStamp||Date.now())-this.startTime;f=this.x;c=this.y;this._unbind(u);this._unbind(r);this._unbind(x);this.options.onBeforeScrollEnd&&this.options.onBeforeScrollEnd.call(this,a);if(this.moved){if(300>j&&this.options.momentum){h=f?this._momentum(f-this.startX,j,-this.x,this.scrollerW-this.wrapperW+this.x,this.options.bounce?this.wrapperW:0):h;b=c?this._momentum(c-this.startY,j,-this.y,0>this.maxScrollY?this.scrollerH-this.wrapperH+this.y:0,this.options.bounce?
this.wrapperH:0):b;f=this.x+h.dist;c=this.y+b.dist;if(0<this.x&&0<f||this.x<this.maxScrollX&&f<this.maxScrollX)h={dist:0,time:0};if(0<this.y&&0<c||this.y<this.maxScrollY&&c<this.maxScrollY)b={dist:0,time:0}}h.dist||b.dist?(q=e.max(e.max(h.time,b.time),10),this.scrollTo(e.round(f),e.round(c),q)):this._resetPos(200)}else{if(g){for(f=q.target;1!=f.nodeType;)f=f.parentNode;if("SELECT"!=f.tagName&&"INPUT"!=f.tagName&&"TEXTAREA"!=f.tagName)c=document.createEvent("MouseEvents"),c.initMouseEvent("click",
!0,!0,a.view,1,q.screenX,q.screenY,q.clientX,q.clientY,a.ctrlKey,a.altKey,a.shiftKey,a.metaKey,0,null),c._fake=!0,f.dispatchEvent(c)}this._resetPos(200)}this.options.onTouchEnd&&this.options.onTouchEnd.call(this,a)}},_resetPos:function(a){var c=0<=this.x?0:this.x<this.maxScrollX?this.maxScrollX:this.x,f=0<=this.y||0<this.maxScrollY?0:this.y<this.maxScrollY?this.maxScrollY:this.y;if(c==this.x&&f==this.y){if(this.moved)this.options.onScrollEnd&&this.options.onScrollEnd.call(this),this.moved=!1}else this.scrollTo(c,
f,a||0)},_mouseout:function(a){var c=a.relatedTarget;if(c)for(;c=c.parentNode;)if(c==this.wrapper)return;this._end(a)},_transitionEnd:function(a){a.target==this.scroller&&(this._unbind("webkitTransitionEnd"),this._startAni())},_startAni:function(){var a=this,c=a.x,f=a.y,h=Date.now(),b,g,j;if(!a.animating)if(a.steps.length){b=a.steps.shift();if(b.x==c&&b.y==f)b.time=0;a.animating=!0;a.moved=!0;a.options.useTransition?(a._transitionTime(b.time),a._pos(b.x,b.y),a.animating=!1,b.time?a._bind("webkitTransitionEnd"):
a._resetPos(0)):(j=function(){var d=Date.now();if(d>=h+b.time)a._pos(b.x,b.y),a.animating=!1,a.options.onAnimationEnd&&a.options.onAnimationEnd.call(a),a._startAni();else if(d=(d-h)/b.time-1,g=e.sqrt(1-d*d),d=(b.x-c)*g+c,a._pos(d,(b.y-f)*g+f),a.animating)a.aniTime=o(j)},j())}else a._resetPos(400)},_transitionTime:function(a){this.scroller.style[d+"TransitionDuration"]=a+"ms"},_momentum:function(a,c,f,b,h){var c=e.abs(a)/c,g=c*c/0.0012,j=0,j=0;0<a&&g>f?(f+=h/(6/(6.0E-4*(g/c))),c=c*f/g,g=f):0>a&&g>
b&&(b+=h/(6/(6.0E-4*(g/c))),c=c*b/g,g=b);return{dist:g*(0>a?-1:1),time:e.round(c/6.0E-4)}},_offset:function(a){for(var c=-a.offsetLeft,f=-a.offsetTop;a=a.offsetParent;)c-=a.offsetLeft,f-=a.offsetTop;return{left:c,top:f}},_bind:function(a,c,f){(c||this.scroller).addEventListener(a,this,!!f)},_unbind:function(a,c,f){(c||this.scroller).removeEventListener(a,this,!!f)},destroy:function(){this.scroller.style[d+"Transform"]="";this._unbind(c,window);this._unbind(j);this._unbind(u);this._unbind(r);this._unbind(x);
this._unbind("mouseout",this.wrapper);this.options.useTransition&&this._unbind("webkitTransitionEnd");this.options.onDestroy&&this.options.onDestroy.call(this)},refresh:function(){var a;this.wrapperW=this.wrapper.clientWidth;this.wrapperH=this.wrapper.clientHeight;this.scrollerW=this.scroller.offsetWidth;this.scrollerH=this.scroller.offsetHeight;this.maxScrollX=this.wrapperW-this.scrollerW;this.maxScrollY=this.wrapperH-this.scrollerH;this.dirY=this.dirX=0;this.hScroll=this.options.hScroll&&0>this.maxScrollX;
this.vScroll=this.options.vScroll&&(!this.options.bounceLock&&!this.hScroll||this.scrollerH>this.wrapperH);a=this._offset(this.wrapper);this.wrapperOffsetLeft=-a.left;this.wrapperOffsetTop=-a.top;this.scroller.style[d+"TransitionDuration"]="0";this._resetPos(200)},scrollTo:function(a,c,f,b){var h=a;this.stop();h.length||(h=[{x:a,y:c,time:f,relative:b}]);for(a=0,c=h.length;a<c;a++){if(h[a].relative)h[a].x=this.x-h[a].x,h[a].y=this.y-h[a].y;this.steps.push({x:h[a].x,y:h[a].y,time:h[a].time||0})}this._startAni()},
scrollToElement:function(a,c){var f;if(a=a.nodeType?a:this.scroller.querySelector(a))f=this._offset(a),f.left+=this.wrapperOffsetLeft,f.top+=this.wrapperOffsetTop,f.left=0<f.left?0:f.left<this.maxScrollX?this.maxScrollX:f.left,f.top=0<f.top?0:f.top<this.maxScrollY?this.maxScrollY:f.top,c=void 0===c?e.max(2*e.abs(f.left),2*e.abs(f.top)):c,this.scrollTo(f.left,f.top,c)},disable:function(){this.stop();this._resetPos(0);this.enabled=!1;this._unbind(u);this._unbind(r);this._unbind(x)},enable:function(){this.enabled=
!0},stop:function(){p(this.aniTime);this.steps=[];this.animating=this.moved=!1}};"undefined"!==typeof exports?exports.iScroll=i:window.iScroll=i})();var requirejs,require,define;
(function(){function e(a){return"[object Function]"===u.call(a)}function d(a){return"[object Array]"===u.call(a)}function i(a,c,f){for(var b in c)if(!(b in G)&&(!(b in a)||f))a[b]=c[b];return n}function g(a,c,b){a=Error(c+"\nhttp://requirejs.org/docs/errors.html#"+a);if(b)a.originalError=b;return a}function m(a,b,f){var h,g,e;for(h=0;e=b[h];h++){e="string"===typeof e?{name:e}:e;g=e.location;if(f&&(!g||0!==g.indexOf("/")&&-1===g.indexOf(":")))g=f+"/"+(g||e.name);a[e.name]={name:e.name,location:g||
e.name,main:(e.main||"main").replace(c,"").replace(j,"")}}}function b(a,c){a.holdReady?a.holdReady(c):c?a.readyWait+=1:a.ready(!0)}function k(c){function f(a,c){var h,b;if(a&&"."===a.charAt(0))if(c){v.pkgs[c]?c=[c]:(c=c.split("/"),c=c.slice(0,c.length-1));h=a=c.concat(a.split("/"));var g;for(b=0;g=h[b];b++)if("."===g)h.splice(b,1),b-=1;else if(".."===g)if(1===b&&(".."===h[2]||".."===h[0]))break;else 0<b&&(h.splice(b-1,2),b-=2);b=v.pkgs[h=a[0]];a=a.join("/");b&&a===h+"/"+b.main&&(a=h)}else 0===a.indexOf("./")&&
(a=a.substring(2));return a}function h(a,c){var b=a?a.indexOf("!"):-1,g=null,e=c?c.name:null,j=a,d,k;-1!==b&&(g=a.substring(0,b),a=a.substring(b+1,a.length));g&&(g=f(g,e));a&&(g?d=(b=t[g])&&b.normalize?b.normalize(a,function(a){return f(a,e)}):f(a,e):(d=f(a,e),k=K[d],k||(k=l.nameToUrl(a,null,c),K[d]=k)));return{prefix:g,name:d,parentMap:c,url:k,originalName:j,fullName:g?g+"!"+(d||""):d}}function j(){var a=!0,c=v.priorityWait,b,h;if(c){for(h=0;b=c[h];h++)if(!y[b]){a=!1;break}a&&delete v.priorityWait}return a}
function d(a,c,b){return function(){var h=x.call(arguments,0),f;if(b&&e(f=h[h.length-1]))f.__requireJsBuild=!0;h.push(c);return a.apply(null,h)}}function k(a,c,b){c=d(b||l.require,a,c);i(c,{nameToUrl:d(l.nameToUrl,a),toUrl:d(l.toUrl,a),defined:d(l.requireDefined,a),specified:d(l.requireSpecified,a),isBrowser:n.isBrowser});return c}function q(a){var c,b,f,d=a.callback,j=a.map,k=j.fullName,s=a.deps;f=a.listeners;if(d&&e(d)){if(v.catchError.define)try{b=n.execCb(k,a.callback,s,t[k])}catch(i){c=i}else b=
n.execCb(k,a.callback,s,t[k]);if(k)(d=a.cjsModule)&&void 0!==d.exports&&d.exports!==t[k]?b=t[k]=a.cjsModule.exports:void 0===b&&a.usingExports?b=t[k]:(t[k]=b,N[k]&&(V[k]=!0))}else k&&(b=t[k]=d,N[k]&&(V[k]=!0));if(C[a.id])delete C[a.id],a.isDone=!0,l.waitCount-=1,0===l.waitCount&&(M=[]);delete P[k];if(n.onResourceLoad&&!a.placeholder)n.onResourceLoad(l,j,a.depArray);if(c)return b=(k?h(k).url:"")||c.fileName||c.sourceURL,f=c.moduleTree,c=g("defineerror",'Error evaluating module "'+k+'" at location "'+
b+'":\n'+c+"\nfileName:"+b+"\nlineNumber: "+(c.lineNumber||c.line),c),c.moduleName=k,c.moduleTree=f,n.onError(c);for(c=0;d=f[c];c++)d(b)}function o(a,c){return function(b){a.depDone[c]||(a.depDone[c]=!0,a.deps[c]=b,a.depCount-=1,a.depCount||q(a))}}function p(a,c){var b=c.map,f=b.fullName,g=b.name,d=Q[a]||(Q[a]=t[a]),e;if(!c.loading)c.loading=!0,e=function(a){c.callback=function(){return a};q(c);y[c.id]=!0;I()},e.fromText=function(a,c){var b=R;y[a]=!1;l.scriptCount+=1;l.fake[a]=!0;b&&(R=!1);n.exec(c);
b&&(R=!0);l.completeLoad(a)},f in t?e(t[f]):d.load(g,k(b.parentMap,!0,function(a,f){var g=[],e,d;for(e=0;d=a[e];e++)d=h(d,b.parentMap),a[e]=d.fullName,d.prefix||g.push(a[e]);c.moduleDeps=(c.moduleDeps||[]).concat(g);return l.require(a,f)}),e,v)}function u(a){C[a.id]||(C[a.id]=a,M.push(a),l.waitCount+=1)}function r(a){this.listeners.push(a)}function z(a,c){var b=a.fullName,f=a.prefix,g=f?Q[f]||(Q[f]=t[f]):null,e,d;b&&(e=P[b]);if(!e&&(d=!0,e={id:(f&&!g?O++ +"__p@:":"")+(b||"__r@"+O++),map:a,depCount:0,
depDone:[],depCallbacks:[],deps:[],listeners:[],add:r},F[e.id]=!0,b&&(!f||Q[f])))P[b]=e;f&&!g?(b=h(f),f in t&&!t[f]&&(delete t[f],delete S[b.url]),f=z(b,!0),f.add(function(){var c=h(a.originalName,a.parentMap),c=z(c,!0);e.placeholder=!0;c.add(function(a){e.callback=function(){return a};q(e)})})):d&&c&&(y[e.id]=!1,l.paused.push(e),u(e));return e}function H(a,c,b,f){var a=h(a,f),e=a.name,g=a.fullName,d=z(a),j=d.id,s=d.deps,i;if(g){if(g in t||!0===y[j]||"jquery"===g&&v.jQuery&&v.jQuery!==b().fn.jquery)return;
F[j]=!0;y[j]=!0;"jquery"===g&&b&&W(b())}d.depArray=c;d.callback=b;for(b=0;b<c.length;b++)if(j=c[b])j=h(j,e?a:f),i=j.fullName,c[b]=i,"require"===i?s[b]=k(a):"exports"===i?(s[b]=t[g]={},d.usingExports=!0):"module"===i?d.cjsModule=s[b]={id:e,uri:e?l.nameToUrl(e,null,f):void 0,exports:t[g]}:i in t&&!(i in C)&&(!(g in N)||g in N&&V[i])?s[b]=t[i]:(g in N&&(N[i]=!0,delete t[i],S[j.url]=!1),d.depCount+=1,d.depCallbacks[b]=o(d,b),z(j,!0).add(d.depCallbacks[b]));d.depCount?u(d):q(d)}function J(a){H.apply(null,
a)}function D(a,c){var b=a.map.fullName,f=a.depArray,h=!0,g,e,d,j;if(a.isDone||!b||!y[b])return j;if(c[b])return a;c[b]=!0;if(f){for(g=0;g<f.length;g++){e=f[g];if(!y[e]&&!Y[e]){h=!1;break}if((d=C[e])&&!d.isDone&&y[e])if(j=D(d,c))break}h||(j=void 0,delete c[b])}return j}function A(a,c){var b=a.map.fullName,f=a.depArray,g,e,d,j;if(!a.isDone&&b&&y[b]){if(b){if(c[b])return t[b];c[b]=!0}if(f)for(g=0;g<f.length;g++)if(e=f[g])if((d=h(e).prefix)&&(j=C[d])&&A(j,c),(d=C[e])&&!d.isDone&&y[e])e=A(d,c),a.depCallbacks[g](e);
return t[b]}}function E(){var c=1E3*v.waitSeconds,c=c&&l.startTime+c<(new Date).getTime(),b="",f=!1,h=!1,e=[],d,k;if(!(0<l.pausedCount)){if(v.priorityWait)if(j())I();else return;for(d in y)if(!(d in G)&&(f=!0,!y[d]))if(c)b+=d+" ";else if(h=!0,-1===d.indexOf("!")){e=[];break}else(k=P[d]&&P[d].moduleDeps)&&e.push.apply(e,k);if(f||l.waitCount){if(c&&b)return c=g("timeout","Load timeout for modules: "+b),c.requireType="timeout",c.requireModules=b,n.onError(c);if(h&&e.length)for(b=0;d=C[e[b]];b++)if(d=
D(d,{})){A(d,{});break}if(!c&&(h||l.scriptCount)){if((s||a)&&!X)X=setTimeout(function(){X=0;E()},50)}else{if(l.waitCount){for(b=0;d=M[b];b++)A(d,{});l.paused.length&&I();5>U&&(U+=1,E())}U=0;n.checkReadyState()}}}}var l,I,v={waitSeconds:7,baseUrl:"./",paths:{},pkgs:{},catchError:{}},B=[],F={require:!0,exports:!0,module:!0},K={},t={},y={},C={},M=[],S={},O=0,P={},Q={},N={},V={},T=0;W=function(a){if(!l.jQuery&&(a=a||("undefined"!==typeof jQuery?jQuery:null))&&!(v.jQuery&&a.fn.jquery!==v.jQuery)&&("holdReady"in
a||"readyWait"in a))if(l.jQuery=a,J(["jquery",[],function(){return jQuery}]),l.scriptCount)b(a,!0),l.jQueryIncremented=!0};I=function(){var a,c,b,f,d,h;l.takeGlobalQueue();T+=1;if(0>=l.scriptCount)l.scriptCount=0;for(;B.length;){a=B.shift();if(null===a[0])return n.onError(g("mismatch","Mismatched anonymous define() module: "+a[a.length-1]));J(a)}if(!v.priorityWait||j())for(;l.paused.length;){d=l.paused;l.pausedCount+=d.length;l.paused=[];for(f=0;a=d[f];f++)c=a.map,b=c.url,h=c.fullName,c.prefix?p(c.prefix,
a):!S[b]&&!y[h]&&(n.load(l,h,b),0!==b.indexOf("empty:")&&(S[b]=!0));l.startTime=(new Date).getTime();l.pausedCount-=d.length}1===T&&E();T-=1};l={contextName:c,config:v,defQueue:B,waiting:C,waitCount:0,specified:F,loaded:y,urlMap:K,urlFetched:S,scriptCount:0,defined:t,paused:[],pausedCount:0,plugins:Q,needFullExec:N,fake:{},fullExec:V,managerCallbacks:P,makeModuleMap:h,normalize:f,configure:function(a){var c,b,f;a.baseUrl&&"/"!==a.baseUrl.charAt(a.baseUrl.length-1)&&(a.baseUrl+="/");c=v.paths;f=v.pkgs;
i(v,a,!0);if(a.paths){for(b in a.paths)b in G||(c[b]=a.paths[b]);v.paths=c}if((c=a.packagePaths)||a.packages){if(c)for(b in c)b in G||m(f,c[b],b);a.packages&&m(f,a.packages);v.pkgs=f}if(a.priority)b=l.requireWait,l.requireWait=!1,I(),l.require(a.priority),I(),l.requireWait=b,v.priorityWait=a.priority;if(a.deps||a.callback)l.require(a.deps||[],a.callback)},requireDefined:function(a,c){return h(a,c).fullName in t},requireSpecified:function(a,c){return h(a,c).fullName in F},require:function(a,b,f){if("string"===
typeof a){if(e(b))return n.onError(g("requireargs","Invalid require call"));if(n.get)return n.get(l,a,b);b=h(a,b);a=b.fullName;return!(a in t)?n.onError(g("notloaded","Module name '"+b.fullName+"' has not been loaded yet for context: "+c)):t[a]}(a&&a.length||b)&&H(null,a,b,f);if(!l.requireWait)for(;!l.scriptCount&&l.paused.length;)I();return l.require},takeGlobalQueue:function(){L.length&&(w.apply(l.defQueue,[l.defQueue.length-1,0].concat(L)),L=[])},completeLoad:function(a){var c;for(l.takeGlobalQueue();B.length;)if(c=
B.shift(),null===c[0]){c[0]=a;break}else if(c[0]===a)break;else J(c),c=null;c?J(c):J([a,[],"jquery"===a&&"undefined"!==typeof jQuery?function(){return jQuery}:null]);n.isAsync&&(l.scriptCount-=1);I();n.isAsync||(l.scriptCount-=1)},toUrl:function(a,c){var b=a.lastIndexOf("."),f=null;-1!==b&&(f=a.substring(b,a.length),a=a.substring(0,b));return l.nameToUrl(a,f,c)},nameToUrl:function(a,c,b){var d,h,e,g,j=l.config,a=f(a,b&&b.fullName);if(n.jsExtRegExp.test(a))c=a+(c?c:"");else{d=j.paths;h=j.pkgs;b=a.split("/");
for(g=b.length;0<g;g--)if(e=b.slice(0,g).join("/"),d[e]){b.splice(0,g,d[e]);break}else if(e=h[e]){a=a===e.name?e.location+"/"+e.main:e.location;b.splice(0,g,a);break}c=b.join("/")+(c||".js");c=("/"===c.charAt(0)||c.match(/^\w+:/)?"":j.baseUrl)+c}return j.urlArgs?c+((-1===c.indexOf("?")?"?":"&")+j.urlArgs):c}};l.jQueryCheck=W;l.resume=I;return l}function h(){var a,c,b;if(H&&"interactive"===H.readyState)return H;a=document.getElementsByTagName("script");for(c=a.length-1;-1<c&&(b=a[c]);c--)if("interactive"===
b.readyState)return H=b;return null}var o=/(\/\*([\s\S]*?)\*\/|([^:]|^)\/\/(.*)$)/mg,p=/require\(\s*["']([^'"\s]+)["']\s*\)/g,c=/^\.\//,j=/\.js$/,u=Object.prototype.toString,r=Array.prototype,x=r.slice,w=r.splice,s=!!("undefined"!==typeof window&&navigator&&document),a=!s&&"undefined"!==typeof importScripts,q=s&&"PLAYSTATION 3"===navigator.platform?/^complete$/:/^(complete|loaded)$/,f="undefined"!==typeof opera&&"[object Opera]"===opera.toString(),G={},z={},L=[],H=null,U=0,R=!1,Y={require:!0,module:!0,
exports:!0},n,r={},J,D,E,M,A,B,F,O,K,W,X;if("undefined"===typeof define){if("undefined"!==typeof requirejs){if(e(requirejs))return;r=requirejs;requirejs=void 0}"undefined"!==typeof require&&!e(require)&&(r=require,require=void 0);n=requirejs=function(a,c,b){var f="_",e;!d(a)&&"string"!==typeof a&&(e=a,d(c)?(a=c,c=b):a=[]);if(e&&e.context)f=e.context;b=z[f]||(z[f]=k(f));e&&b.configure(e);return b.require(a,c)};n.config=function(a){return n(a)};require||(require=n);n.toUrl=function(a){return z._.toUrl(a)};
n.version="1.0.5";n.jsExtRegExp=/^\/|:|\?|\.js$/;D=n.s={contexts:z,skipAsync:{}};if(n.isAsync=n.isBrowser=s)if(E=D.head=document.getElementsByTagName("head")[0],M=document.getElementsByTagName("base")[0])E=D.head=M.parentNode;n.onError=function(a){throw a;};n.load=function(a,c,f){n.resourcesReady(!1);a.scriptCount+=1;n.attach(f,a,c);if(a.jQuery&&!a.jQueryIncremented)b(a.jQuery,!0),a.jQueryIncremented=!0};define=function(a,c,b){var f,g;"string"!==typeof a&&(b=c,c=a,a=null);d(c)||(b=c,c=[]);!c.length&&
e(b)&&b.length&&(b.toString().replace(o,"").replace(p,function(a,b){c.push(b)}),c=(1===b.length?["require"]:["require","exports","module"]).concat(c));if(R&&(f=J||h()))a||(a=f.getAttribute("data-requiremodule")),g=z[f.getAttribute("data-requirecontext")];(g?g.defQueue:L).push([a,c,b])};define.amd={multiversion:!0,plugins:!0,jQuery:!0};n.exec=function(a){return eval(a)};n.execCb=function(a,c,b,f){return c.apply(f,b)};n.addScriptToDom=function(a){J=a;M?E.insertBefore(a,M):E.appendChild(a);J=null};n.onScriptLoad=
function(a){var c=a.currentTarget||a.srcElement,b;if("load"===a.type||c&&q.test(c.readyState))H=null,a=c.getAttribute("data-requirecontext"),b=c.getAttribute("data-requiremodule"),z[a].completeLoad(b),c.detachEvent&&!f?c.detachEvent("onreadystatechange",n.onScriptLoad):c.removeEventListener("load",n.onScriptLoad,!1)};n.attach=function(c,b,e,d,h,g){var j;if(s)return d=d||n.onScriptLoad,j=b&&b.config&&b.config.xhtml?document.createElementNS("http://www.w3.org/1999/xhtml","html:script"):document.createElement("script"),
j.type=h||b&&b.config.scriptType||"text/javascript",j.charset="utf-8",j.async=!D.skipAsync[c],b&&j.setAttribute("data-requirecontext",b.contextName),j.setAttribute("data-requiremodule",e),j.attachEvent&&!f?(R=!0,g?j.onreadystatechange=function(){if("loaded"===j.readyState)j.onreadystatechange=null,j.attachEvent("onreadystatechange",d),g(j)}:j.attachEvent("onreadystatechange",d)):j.addEventListener("load",d,!1),j.src=c,g||n.addScriptToDom(j),j;a&&(importScripts(c),b.completeLoad(e));return null};if(s){A=
document.getElementsByTagName("script");for(O=A.length-1;-1<O&&(B=A[O]);O--){if(!E)E=B.parentNode;if(F=B.getAttribute("data-main")){if(!r.baseUrl)A=F.split("/"),B=A.pop(),A=A.length?A.join("/")+"/":"./",r.baseUrl=A,F=B.replace(j,"");r.deps=r.deps?r.deps.concat(F):[F];break}}}n.checkReadyState=function(){var a=D.contexts,c;for(c in a)if(!(c in G)&&a[c].waitCount)return;n.resourcesReady(!0)};n.resourcesReady=function(a){var c,f;n.resourcesDone=a;if(n.resourcesDone)for(f in a=D.contexts,a)if(!(f in G)&&
(c=a[f],c.jQueryIncremented))b(c.jQuery,!1),c.jQueryIncremented=!1};n.pageLoaded=function(){if("complete"!==document.readyState)document.readyState="complete"};if(s&&document.addEventListener&&!document.readyState)document.readyState="loading",window.addEventListener("load",n.pageLoaded,!1);n(r);if(n.isAsync&&"undefined"!==typeof setTimeout)K=D.contexts[r.context||"_"],K.requireWait=!0,setTimeout(function(){K.requireWait=!1;K.scriptCount||K.resume();n.checkReadyState()},0)}})();
define("requireLib",function(){});
(function(){var e,d,i,g,m,b,k,h,o,p,c,j,u,r=Array.prototype.slice,x=Object.prototype.hasOwnProperty,w=function(c,a){function b(){this.constructor=c}for(var f in a)x.call(a,f)&&(c[f]=a[f]);b.prototype=a.prototype;c.prototype=new b;c.__super__=a.prototype;return c};e="function"===typeof("undefined"!==typeof console&&null!==console?console.error:void 0)&&function(c){return console.error(c)}||function(){};m=this;i=m.document||{createElement:function(){}};p="object"===typeof Node?function(c){return c instanceof
Node}:function(c){return"object"===typeof c&&"number"===typeof c.nodeType&&"string"===typeof c.nodeName};o=Array.isArray?Array.isArray:function(){return function(c){return c.push===push&&null!=c.length}}();b=Function.prototype.bind?function(c,a){return c.bind(a)}:function(c,a){return function(){return c.apply(a,arguments)}};k=function(){return i.createElement("div")};j=i.createRange();h=function(c){c=j.createContextualFragment(c).childNodes[0];return 1===c.nodeType&&c};u=function(c,a){for(var b,f;0<
a.length;)if(null!=(b=a.shift()))p(b)?c.appendChild(b):"string"===(f=typeof b)||"number"===f?c.appendChild(i.createTextNode(b)):o(b)?Array.prototype.unshift.apply(a,b):e("renderNodes: unsupported child type = "+b);return c};m.cell=d=function(){function c(a){var e,f,d,g,h,j,k;this.options=null!=a?a:{};if(null!=this.options.model)this.model=this.options.model;"function"===typeof this.init&&this.init(this.options);this.$el=jQuery(this.el=this._tag());if(a=this.options.id)this.el.id=a;k=[this.cell.prototype.name,
this["class"],this.options["class"]];for(a=0,j=k.length;a<j;a++)if(h=k[a])this.el.className+=a&&" "+h||h;u(this.el,o(d="function"===typeof this.render?this.render(this.$R):void 0)&&d||[]);a=this.on;for(e in a)if(d=a[e],"function"===typeof d&&(g=/^([A-z]+)(\s(.*))?$/.exec(e))&&(f=g[1]))this.$el.on(f,g[3],b(d,this));"function"===typeof this.afterRender&&this.afterRender()}c.prototype.$=function(a){return jQuery(a,this.el)};c.prototype.$R=function(){var a,c,b,d,g,j,k,m;a=arguments[0];c=arguments[1];
b=3<=arguments.length?r.call(arguments,2):[];if(a){if((null!=c?c.constructor:void 0)!==Object)b.unshift(c),c=void 0;return(k=function(){if("string"===typeof a){if(j=/^(\w+)?(#([\w\-]+))*(\.[\w\.\-]+)?$/.exec(a)){d=i.createElement(j[1]||"div");(m=j[3])&&d.setAttribute("id",m);if(c)for(g in"class"in c&&(d.className+=c["class"],c["class"]=void 0),c)m=c[g],d.setAttribute(g,m);if(m=j[4])d.className+=m.replace(/\./g," ");return d}return/^<[A-z]/.test(a)?h(a):e("renderParent: unsupported parent string = '"+
a+"'")}return a.prototype.cell===a?(new a(c)).el:p(a)?a:e("renderParent: unsupported parent type = "+a)}())&&u(k,b)}};return c}();d.extend=function(c){var a,b,f,e,g;null==c&&(c={});if("object"!==typeof c)throw"cell.extend(): expects an object {render,init,name}";if(c.init&&"function"!==typeof c.init||c.render&&"function"!==typeof c.render)throw"cell.extend(): expects {render,init} to be functions";a=function(){function a(){a.__super__.constructor.apply(this,arguments)}w(a,d);return a}();for(b in c)g=
c[b],a.prototype[b]=g;a.prototype.cell=a;a.prototype._tag="string"===(e=typeof c.tag)?function(){return h(c.tag)||k()}:"function"===e?function(){return h(this.tag())||k()}:k;if("string"===typeof(b=c.css))f=i.createElement("style"),f.innerHTML=b;else if("string"===typeof(b=c.css_href))f=i.createElement("link"),f.href=b,f.rel="stylesheet";if(f)f.type="text/css",$("head")[0].appendChild(f);return a};"function"===typeof define&&"function"===typeof require&&(c=/(.*\/)?(.*)$/,define("cell",[],g={pluginBuilder:"cell-builder-plugin",
load:function(b,a,h){a([b],function(f){var j;if("object"!==typeof f)e("Couldn't load "+b+" cell. cell definitions should be objects, but instead was "+typeof f);else{f.name=c.exec(b)[2];if(null==(null!=(j=g.__preinstalledCells__)?j[b]:void 0)&&null==f.css_href)f.css_href=a.toUrl(""+b+".css");"string"===typeof f["extends"]?a(["cell!"+f["extends"]],function(a){a.prototype.name&&(f["class"]=a.prototype.name+(" "+f["class"])||"");h(a.extend(f))}):h(d.extend(f))}})}}),jQuery(i).ready(function(){j.selectNode(i.body);
jQuery("[data-cell]").each(function(){var c,a,b,f,d=this;if(b=this.getAttribute("data-cell")){f={};c=/(^\?cachebust)|(&cachebust)/.test(m.location.search);if((null!==(a=this.getAttribute("data-cell-cachebust"))||c)&&"false"!==a)f.urlArgs="bust="+(new Date).getTime();if(c=this.getAttribute("data-cell-baseurl"))f.baseUrl=c;require(f,["cell!"+b],function(a){jQuery(d).append((new a).el)})}})}))}).call(this);
define("AppConfig",["cell!pages/schedule/Schedule"],function(){return{contexts:{Schedule:{defaultPagePath:"pages/schedule/Schedule"},Watch:{defaultPagePath:"pages/watch/Watch"},Search:{defaultPagePath:"pages/watch/Watch"}},defaultContext:"Schedule"}});var __slice=Array.prototype.slice;
define("data/JSONP",[],function(){var e,d,i,g;d=function(d){return d};g=0;i=function(d){var b,e;b="__jsonp"+ ++g;window[b]=function(e){d.success(e);window[b]=void 0;return $("#"+b).remove()};if(null==d.callback)d.callback="callback";e=document.createElement("script");e.id=b;e.setAttribute("type","text/javascript");e.setAttribute("src",""+d.url+(-1===d.url.indexOf("?")&&"?"||"&")+d.callback+"="+b);return $("head").append(e)};e=-1<window.location.search.indexOf("mock-service=true")?function(d,b){var e,
g;e=d.mock;g=d.real;return setTimeout(function(){return require([e],function(d){return b("function"===typeof d?d(g):d)})},0)}:function(d,b){return i({callback:"jsonp",url:d.real,success:b||function(){}})};return{JSONPService:function(){return function(g,b){var k,h,i,p,c,j,u=this;k=b.baseURL;c=b.process;h=b.methods;null==c&&(c=d);j=function(b,h){var j,i,a;i=c;j=d;if("object"===(a=typeof h)&&"function"!==a){if(null!=h.process)i=h.process;h=h.path;if(null!=h.getCache)j=h.getCache}"string"===typeof h&&
function(){var a;a=h;return h=function(){return a}}();return u[b]=function(){var a,c,p,o;a=2<=arguments.length?__slice.call(arguments,0,o=arguments.length-1):(o=0,[]);p=arguments[o++];null==p&&(p=d);void 0!==(c=j())?p(c):e({mock:"data/mock/"+g+"/"+b,real:k+h.apply(null,a)},function(a){a=i(a);p(a)})}};for(i in h)p=h[i],j(i,p)}}()}});
define("data/UserService",["data/JSONP"],function(e){return new e.JSONPService("users",{baseURL:"api/users/",methods:{getWatchedShows:function(){return"pwong/watched-shows"},getShows:function(d){return"pwong/schedule/"+(d.getYear()+1900)+"-"+d.getMonth()+"-"+d.getDate()}}})});define("data/ActorService",["data/JSONP"],function(e){return new e.JSONPService("actors",{baseURL:"api/actors/",methods:{getDetails:function(d){return""+d}}})});
define("data/ShowService",["data/JSONP"],function(e){return new e.JSONPService("shows",{baseURL:"api/shows/",methods:{getDetails:function(d){return""+d}}})});define("Services",["data/UserService","data/ActorService","data/ShowService"],function(e,d,i){return{user:e,show:i,actor:d}});
define("shared/DateHelper",[],function(){var e,d,i;i=new Date;d=["Today","Yesterday"].concat(function(){var d;d=[];for(e=2;7>e;e++)d.push(""+e+" days ago");return d}(),"a week ago");return{getDisplayable:function(e){return i.getYear()===e.getYear()&&i.getMonth()===e.getMonth()?d[i.getDate()-e.getDate()]:e.toLocaleDateString()}}});
define("pages/schedule/Schedule",["require","Services","shared/DateHelper","cell!shared/ListView"],function(e,d,i,g){return{init:function(){var d=this;return this.model.bind({activate:function(){d.model.set({title:i.getDisplayable(new Date)});return d.$("#ShowList").trigger("resetActive")}})},render:function(i){var b=this;return d.user.getShows(new Date,function(d){var h;b.$el.append(i(g,{id:"ShowList",list:function(){var b,e,c;c=[];for(b=0,e=d.length;b<e;b++)h=d[b],c.push({link:this.pageURI("pages/showdetails/ShowDetails",
{id:h.id,title:h.title}),text:h.title});return c}.call(b)}));b.model.trigger("refreshScroller");return e(["pages/showdetails/ShowDetails"],function(){})})}}});
define("shared/ListView",{tag:"<ul>",render:function(e){var d,i,g,m,b,k,h,o;if(g=this.options.list){o=[];for(b=0,k=g.length;b<k;b++)if(h=g[b],m=h.text,i=h.link,d=h.dividerText,m||d)m?o.push(e("<li data-navto='"+i+"'>",e("div"),m)):o.push(e("li.divider",d));return o}},on:{resetActive:function(){return this.$("li.active").removeClass("active").addClass("deactive")},"webkitAnimationEnd li > div":function(){return this.$("li.deactive").removeClass("deactive")},"click li":function(e){e=e.target;this.$("li.active").removeClass("active");
return $(e).closest("li").addClass("active")}}});define("HashDelegate",{set:function(e){return window.location.hash=e},get:function(){return window.location.hash},onChange:function(e){return $(window).on("hashchange",e)}});
define("framework/Model",[],function(){var e,d;e=/^change:(.*)/;d=function(d,e){var m,b,k;for(b=0,k=d.length;b<k;b++)if(m=d[b],m===e)return;return d.unshift(e)};return function(){function i(b){var d,e;this._ls={};for(d in b)e=b[d],this[d]=e}var g,m;i.pathObj=m=function(b,d){var e,g;if(b){g=d.length;for(e=0;e<g&&null!=(b=b[d[e++]]););return b}};i.parsePropChange=g=function(b){var d,g;return null!=(d=e.exec(b))?null!=(g=d[1])?g.split("."):void 0:void 0};i.prototype.set=function(b,d){var e,g,i;for(e in b)if(i=
b[e],this[e]!==i){g=this[e];try{this.trigger({cur:this[e]=i,prev:g,property:e,type:"change:"+e,data:d})}catch(c){}}};i.prototype.trigger=function(b,d){var e,g,i,c,j;e="string"===typeof b?{type:b,data:d}:b;e.model=this;if(i=this._ls[e.type])for(c=0,j=i.length;c<j;c++){g=i[c];try{g(e)}catch(m){}}};i.prototype.bindAndCall=function(b){var e,h,o,p;h=this;p=function(c){var b,e,k,p,w,s,a,q,f,G,z;if(s=g(o)){e=s.length-1;f=s[e];w=s.slice(0,e);a=function(a,c){var b,e,f;return d(null!=(f=(b=c._ls)[e="change:"+
s[a]])?f:b[e]=[],q[a])};k=h;q=[];G=function(b){q[b]=function(d){for(var g=b,h=d.cur,j=d.prev,k=d.model;g++<e;h=(k=h)&&h[s[g]],j=j&&j[s[g]])h instanceof i&&a(g,h);g={cur:h,prev:j,property:f,type:"change:"+f,model:k,data:d.data};if(b!==e)g.parentEvent=d;return c(g)};if(k instanceof i)return a(b,k),k=k[p]};for(b=0,z=s.length;b<z;b++)p=s[b],G(b);try{return c({cur:k,property:f,type:o,model:m(h,w)})}catch(L){return console.error((null!=L?L.stack:void 0)||L)}}else{d(null!=(w=(b=h._ls)[o])?w:b[o]=[],c);try{return c({type:o,
model:h})}catch(H){}}};for(o in b)e=b[o],p(e)};i.prototype.bind=function(b){var e,h,m,p,c,j,u,r,x,w;for(p in b){h=b[p];if(e=g(p)){x=e.slice(0,-1);for(u=0,r=x.length;u<r;u++)if(m=x[u],(c=this[m])instanceof i)e={},e["change:"+m]=function(){},c.bind(e)}d(null!=(w=(j=this._ls)[p])?w:j[p]=[],h)}};i.prototype.unbind=function(b){var e,d,g,i,c,j;for(c in b)if(e=b[c],i=this._ls[c])for(d=0,j=i.length;d<j;d++)g=i[d],g===e&&delete i[d]};return i}()});
define("framework/Nav",["AppConfig","HashDelegate","./Model"],function(e,d,i){var g,m,b,k,h,o,p;k=/^\#([^!^?]+)(!([^?]+))?(\?(.+))?/;h=!1;g=new i({_toHash:p=function(c){var b,d;b=c.context;d=c.page;c=c.data;b=e.contexts[b]&&b||e.defaultContext;return"#"+b+"!"+(d||e.contexts[b].defaultPagePath)+(c&&"?"+encodeURIComponent(JSON.stringify(c))||"")},_parseHash:o=function(c){var b,d,g,h,i;i=k.exec(c);return{hash:c,context:b=(d=null!=i?i[1]:void 0)&&e.contexts[d]&&d||e.defaultContext,page:(h=null!=i?i[3]:
void 0)&&"/"!==h.substr(-1)&&h||e.contexts[b].defaultPagePath,data:(g=null!=i?i[5]:void 0)&&JSON.parse(decodeURIComponent(g))}},current:function(){var c,b;b=o(d.get());if(b.hash!==(c=p(b)))b.hash=c,h=!0;return new i(b)}(),canBack:function(){var c;return 1<(null!=(c=m[g.current.context])?c.length:void 0)},goBack:function(){var c,b;if(c=null!=(b=m[g.current.context][1])?b.hash:void 0)return d.set(c)},pageHash:function(c,b){return p({context:g.current.context,page:c,data:b})},switchContext:function(c){var b;
if("string"===typeof c&&(b=m[c])&&g.current.context!==c)return d.set(p(b[0]||{context:c,page:e.contexts[c].defaultPage}))}});m={};for(b in e.contexts)m[b]=[];m[g.current.context].push(g.current);g.bind({"change:current":function(c){var b,d,e;b={};for(d in c)e=c[d],b[d]=e;b.type="change:current[context="+c.cur.context+"]";return g.trigger(b)}});d.onChange(function(){var c,b,e;if(h)h=!1;else if(b=o(d.get()),c=m[b.context],g.current.context!==b.context)g.set({current:c.length?c[0]:(c.unshift(b=new i(b)),
b)},{isBack:!1,isContextSwitch:!0});else if(b.hash===(null!=(e=c[1])?e.hash:void 0))b=c[1],c.shift(),g.set({current:b},{isBack:!0,isContextSwitch:!1});else if(0===c.length||c[0].hash!==b.hash)c.unshift(b=new i(b)),g.set({current:b},{isBack:!1,isContextSwitch:!1})});h&&d.set(g.current.hash);return g});
var __hasProp=Object.prototype.hasOwnProperty,__extends=function(e,d){function i(){this.constructor=e}for(var g in d)__hasProp.call(d,g)&&(e[g]=d[g]);i.prototype=d.prototype;e.prototype=new i;e.__super__=d.prototype;return e};
define("framework/ContextModel",["./Model"],function(e){return function(d){function i(d){var m,b,k,h,o,p=this;k=d.id;h=d.initialHash;b=d.hashManager;d=d.defaultPagePath;i.__super__.constructor.call(this,{id:k,defaultPagePath:d,currentPageModel:m=new e(h),pageHistory:o=[m]});(m={})["change:current[context="+k+"]"]=function(c){var b,d;b=c.cur;c=c.prev;if(!(c=b.context!==(null!=c?c.context:void 0)))(null!=(d=o[1])?d.hash:void 0)===b.hash?o.splice(0,1):o.unshift(new e(b));return p.set({currentPageModel:o[0]},
{isContextSwitch:c})};b.bind(m)}__extends(i,d);return i}(e)});
define("framework/Context",["require","./Model","./Nav","cell!./Page"],function(e,d,i,g){return{tag:function(){return"<div data-ctxid='"+this.options.contextid+"'>"},afterRender:function(){var d,b,e,h,o;o={};e=null;d=this.$el;h=(b={})["change:current[context="+this.options.contextid+"]"]=function(b){var c,h,i,r,x,w;c=b.cur;r=b.prev;i=b.data,b=i.isBack,h=i.isContextSwitch;if(!h){i=o[c.hash];if((x=r&&o[r.hash])&&b)o[r.hash]=void 0,x.$el.bind("webkitAnimationEnd",function(){return x.$el.remove()});i||
(i=o[c.hash]=new g({model:c}));i.$el.prependTo(d);c="Page animate "+((null!=r?r.context:void 0)===c.context?(w=b&&"-reverse"||"",null!=e&&e.$el.attr("class","Page animate headingOut"+w),null!=e&&e.model.trigger("deactivate"),"headingIn"+w):"fadeIn");i.$el.attr("class",c);return(e=i).model.trigger({type:"activate",isback:b})}};i.bind(b);return h({cur:this.options.initialHash,data:{isBack:!1}})}}});
define("framework/Page",["require","./Nav"],function(e,d){return{tag:function(){return"<div data-cellpath='"+this.model.page+"'>"},render:function(i){var g=this;return e(["cell!"+this.model.page],function(e){e.prototype.pageURI=d.pageHash;g.$el.append(i(e,{model:g.model}));return g.pageRendered()})},pageRendered:function(){var d,e,m=this;d=!0;this.model.bind({deactivate:function(){return d=!1}});this.model.bind({activate:function(){d=!0;return m.$el.css("visibility","visible")}});this.$el.bind("webkitAnimationEnd",
function(){if(!d)return m.$el.css("visibility","hidden")});e=new iScroll(this.el);return this.model.bindAndCall({refreshScroller:function(){return e.refresh()}})}}});require(["cell"],function(e){e.__preinstalledCells__={"framework/App":0,"pages/schedule/Schedule":0,"shared/ListView":0,"framework/Context":0,"framework/ContextNavBar":0,"framework/Page":0,"framework/TitleBar":0}});var hideAddressBar,ua;document.addEventListener("touchmove",function(e){return e.preventDefault()});
hideAddressBar=function(){var e,d;e=0;setTimeout(d=function(){if(1===++e)return window.scrollTo(0,1)},500);return $(window).bind("resize",function(){e=0;return d()})};$("body").attr("class",(ua=navigator.userAgent).match(/iPhone/i)||ua.match(/iPod/i)||ua.match(/iPad/i)?window.navigator.standalone?"IOSFullScreen":(hideAddressBar(),"IOS"):(hideAddressBar(),"ANDROID"));
define("framework/App","./Nav,./Model,./ContextModel,cell!./Context,cell!./ContextNavBar,cell!./TitleBar".split(","),function(e,d,i,g,m,b){var k;k={};return{render:function(d){return[d(b),d("#content"),d(m)]},afterRender:function(){var b,d=this;b=this.$("#content");return e.bindAndCall({"change:current":function(e){var c,i,m;c=e.cur;i=e.prev;e=e.data;if(!e||null!=e&&e.isContextSwitch){if(!(e=k[c.context]))e=k[c.context]=new g({contextid:c.context,initialHash:c}),b.append(e.$el);e.$el.toggle(!0);if(i=
null!=i?i.context:void 0)null!=(m=k[i])&&m.$el.toggle(!1);e?(d.$("#content > .activeTab").removeClass("activeTab"),e.$el.toggle(!0).toggleClass("activeTab",!0)):"undefined"!==typeof console&&null!==console&&"function"===typeof console.log&&console.log("Could not switch to context = '"+c.context+"'")}}})},on:{"click [data-navto]":function(b){return location.hash=$(b.target).closest("[data-navto]").data("navto")}}}});
define("framework/ContextNavBar",["AppConfig","./Nav"],function(e,d){return{tag:"<ul>",render:function(d){var g,m,b,k;b=e.contexts;k=[];for(g in b)m=b[g].text,k.push(d("<li data-ctxid='"+g+"'>",m||g));return[k]},on:{"click li":function(e){e=e.target;$("li.active").removeClass("active");return d.switchContext($(e).addClass("active").data("ctxid"))}}}});
define("framework/TitleBar",["framework/Nav"],function(e){return{render:function(d){return[d("#backbutton",d("span","Back")),d("#titles",d("#title"),d("#prevtitle")),d("#gobutton",d("span","Do It"))]},afterRender:function(){var d,i,g,m;m=!1;d=this.$("#backbutton");this.$("#backbutton > span");g=this.$("#title");i=this.$("#prevtitle");g.bind("webkitAnimationEnd",function(){g.attr("class","");i.attr("class","");return m=!1});return e.bindAndCall({"change:current.title":function(b){var k,h;k=b.cur;h=
b.prev;b=b.data;b=null!=b?b.isBack:void 0;g.html(k||"");if(!m)return d.css("visibility",e.canBack()&&"visible"||"hidden"),k=b&&"-reverse"||"",h&&i.html(h).attr("class","animate headingOut"+k),g.attr("class","animate headingIn"+k),m=!0}})},on:{"click #backbutton":function(){return e.goBack()}}}});
